### ISSUE TITLE
Use initial_layout from circuit metadata as initial_layout in transpiler

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#10118]
### What should we add?

It should be possible to do this:

```python
transpile(qc2, backend, initial_layout=trans_qc._layout.initial_layout)
```

Currently you get:

```python
TranspilerError: 'FullAncillaAllocation: The layout refers to a qubit that does not exist in circuit.'
```

**Comment by mtreinish** [comment]
I assume qc2 is a similar circuit to whatever the input was that generated `trans_qc`. It looks like the cause of this is two-fold, the first is the way ancilla allocation is done we're modifying the initial layout in place so that it has all the idle qubits set in the layout. The way I'd normally think to fix this is just store the layout in a separate property before ancilla insertion so that the initial layout is just the input qubits. But, `VF2PostLayout` actually complicates this a bit because we can set the layout post-routing we might end up with a wider circuit than the input due to inserted swaps and it will always work on the wider layout, but we want to ensure the layout in initial layout reflects what `VF2PostLayout` selects. I think to do this accurately we need to store the input layout to `FullAncillaAllocation` so we store it prior to ancilla allocation, and also update `ApplyLayout` to update that based on the partial output of `VF2PostLayout`. I think doing that for 0.24.1 is probably in scope.

I do think we probably should also return the full width initial layout because I think it would be also be useful depend on your use case, but I think that also relates to #9476 and how we want to handle ancilla expansion in the layout.

**Comment by jakelishman** [comment]
If I remember this issue correctly, #10835 should have largely addressed it since `TranspileLayout` now has an `initial_index_layout` method.  The top line can now be:
```python
transpile(qc2, backend, initial_layout=trans_qc.layout.initial_index_layout(filter_ancillas=True))
```
and I believe it should work as expected.

Feel free to re-open if I missed something.
