### ISSUE TITLE
Classical_function does not work with GroverOperator

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#10255]
### Environment

- **Qiskit Terra version**:  latest
- **Python version**: 
- **Operating system**: 

### What is happening?

The documentation (https://qiskit.org/documentation/apidoc/classicalfunction.html) shows how to construct a classical oracle for a problem such a Grover search.  However, the resulting circuit uses an ancilla qubit, whereas the `GroverOperator`  (https://qiskit.org/documentation/stubs/qiskit.circuit.library.GroverOperator.html) from the circuit library only works with oracle circuits with no ancilla, i.e. formed using only multi-controlled Z gates.

### How can we reproduce the issue?

Try using a circuit generated by using `classical_function` in the `GroverOperator` 

### What should happen?

The classical oracle generating tools should be compatible with the circuit library components that make use of them

**Comment by Cryoris** [comment]
The issue here is that Grover's algorithm is defined on a phaseflip oracle, where the coefficients of the solution states are multiplied by $-1$, but the `classical_function` module computes bitflip oracles, where a target qubit is flipped if the state encodes a solution. 

We can transform the bitflip to phaseflip oracle for Grover in different ways:
1. Use a custom synthesizer in `classicalfunction.synth()` (pretty cumbersome)
2. Use the `PhaseOracle`, which does 1. for you
3. Manually transform bit to phaseflip by adding some extra gates

It might be convenient to add a keyword argument to the classicalfunction synthesis to do phaseflip oracles instead of bitflip. This would remove the need for the `PhaseOracle` and allows to drop auxiliary qubits that the bitflip oracles need in a lot of cases.

To see the current workflow in action, here's option 2 for the oracle with 4 variables `a b c d` and solution `not a and not b and c and d`:
```python
from qiskit.circuit.library import PhaseOracle, GroverOperator

phase_oracle = PhaseOracle("~a & ~b & c & d")
print("Phase oracle:", phase_oracle.draw())  
grover_op = GroverOperator(phase_oracle)
```
Note that this does not need an auxiliary qubit as it's just an MCZ.

Here's option 3:
```python
from qiskit.circuit import QuantumCircuit
from qiskit.circuit.library import GroverOperator
from qiskit.circuit.classicalfunction import classical_function
from qiskit.circuit.classicalfunction.types import Int1

# the oracle defined as bit-flip oracle, where the output bit
# is flipped if the state is good
@classical_function
def grover_oracle(a: Int1, b: Int1, c: Int1, d: Int1) -> Int1:
    return (not a and not b and c and d)

bit_oracle = grover_oracle.synth()
print("Bit oracle:\n", bit_oracle.draw())

# Option 3: translate to a phaseflip oracle, where the phase of the
# good state is multilpied by (-1)
n = bit_oracle.num_qubits
phase_oracle = QuantumCircuit(n)
phase_oracle.x(n - 1)
phase_oracle.h(n - 1)
phase_oracle.compose(bit_oracle, inplace=True)
phase_oracle.h(n - 1)
phase_oracle.x(n - 1)

print("Phase oracle:\n", phase_oracle.draw())

# construct the Grover operator from it
grover_op = GroverOperator(phase_oracle)
```

Both are equally valid and we can verify the result with the `Grover` algorithm:
```python
from qiskit.algorithms import Grover, AmplificationProblem
from qiskit.primitives import Sampler

problem = AmplificationProblem(
    phase_oracle,
    objective_qubits=list(range(4)),  # the qubits we want to measure (exclude auxiliary output qubit)
    is_good_state=lambda x: x == "1100"  # allows to check if we found the right solution (not used to determine the solution)
)

# get the optimal number of rotations (since we know the number of solutions)
optimal_power = Grover.optimal_num_iterations(num_solutions=1, num_qubits=4)

# run Grover
grover = Grover(sampler=Sampler(), iterations=[optimal_power])
result = grover.amplify(problem)
```
Prints:
```
{   'assignment': '1100',
    'circuit_results': [...]
    'iterations': [3],
    'max_probability': 0.9613189697265564,
    'oracle_evaluation': True,
    'top_measurement': '1100'}
```

**Comment by 1ucian0** [comment]
Hi @nonhermitian , did  @Cryoris answer this issue? Can it be closed? Can be rephrase as a documentation isssue?

**Comment by 1ucian0** [comment]
Let's close it for now and, if necessary, it can be reopened.

**Comment by nonhermitian** [comment]
It does not look like anything was changed or fixed, nor was the docs updated to resolve the inconsistency. I would not called this "completed". If you want to close this without resolving the issue itself then a "won't fix" is probably the way to go.
