### ISSUE TITLE
Support np.sign for parameter

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit#10360]
### What should we add?

I sometime want to check sign of parameter value, but this is not currently supported.

```python
from qiskit.circuit import Parameter
import numpy as np

v = Parameter("value")
np.sign(v)
```

(temporary hack)
```python
from qiskit.circuit import ParameterExpression
import symengine as sym

sign_of_v = ParameterExpression(
    symbol_map={v: v._symbol_expr},
    expr=sym.sign(v._symbol_expr),
)
```

It would be great if Qiskit can support this without above ugly hack.

**Comment by SamD-1998** [comment]
Hey, I can work on this. Can you assign it to me?

**Comment by SamD-1998** [comment]
I can add a method inside the function definition of `Parameter`. Perhaps that's simpler and prevents you from importing `numpy`. Would you want that?

**Comment by wshanks** [comment]
I wouldn't use numpy. I would do something similar to what is done for other functions like this one:

https://github.com/Qiskit/qiskit-terra/blob/2b225d3713a8ef160a38e8fbfbc7d08a0b8a4682/qiskit/circuit/parameterexpression.py#L377-L386

The main thing is to add a `sign` method so that the user does not need to access the private `_sybol_expr` attribute.

**Comment by SamD-1998** [comment]
Hi, I think I have a working code that implements this. The contribution guidelines say that I have to open a Draft pull request and prepend the title with the WIP tag. How do I do this?

**Comment by wshanks** [comment]
Opening a draft pull request instead of a normal pull request just requires selecting an option from a drop down on open pull request page. See the screenshot on [this page](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

Prepending the title just means putting the text "WIP" at the beginning of the title text box when opening the pull request.

Opening a pull request is a little more involved and there are several ways to do it. Maybe [this page](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) from GitHub is a good starting point.

**Comment by SamD-1998** [comment]
Hi, I tried pushing my branch to a new remote branch in this qiskit-terra repo but I got a permission denied error. What should I do?

**Comment by wshanks** [comment]
Yes, only a limited set of people can modify the Qiskit/qiskit-terra repo. You need to create a fork of the repo in your account, add your branch to your repo, and then create the pull request in the Qiskit/qiskit-terra repo from your fork (probably called SamD-1998/qiskit-terra). There is some description of forks [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks) and about creating a pull request across forks [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by SamD-1998** [comment]
I've initiated a PR in the `base repository: Qiskit/qiskit-terra` and `base: main`. I might have to make a note somewhere about how to use this feature. Do I need to include a docstring somewhere to mention it to a user?

**Comment by wshanks** [comment]
Yes, adding a docstring is good. We can move the discussion to #10571.
