### ISSUE TITLE
Add 1xp docs announcement section to documentation home page

### ISSUE THREAD

**Issue by mackinziblank** [Qiskit/qiskit#10594]
To announce the new documentation experience being released, we should add this announcement section on the documentation home page.

<img width="932" alt="image" src="https://github.com/Qiskit/qiskit_sphinx_theme/assets/59657965/c0606c5a-f94a-43f8-b109-49c975ce457b">

fyi @javabster

**Comment by javabster** [comment]
Because this homepage is generated with Sphinx we are somewhat limited in how we can style components that sit within the body of the page. We have 2 options, a Qiskit Card directive or a Qiskit CTA directive:

Qiskit Card Directive - provides the full width box with an image, the entire box is clickable:

<img width="982" alt="Screenshot 2023-08-08 at 5 46 50 PM" src="https://github.com/Qiskit/qiskit-terra/assets/23662430/4c2dc8be-c526-4603-b65d-22a1d1b68d21">

Qiskit CTA directive - doesn't have a full width box but has text and a grey button that could include CTA text

<img width="506" alt="Screenshot 2023-08-08 at 5 48 04 PM" src="https://github.com/Qiskit/qiskit-terra/assets/23662430/c6df410d-b0f2-45fe-ad61-4689b1d84344">

@mackinziblank which do you think would be better?

**Comment by JulesMurphy** [comment]
@javabster I prefer the first option personally, as it is more visually prominent. Is there any way to include link text within the content in option 1?

**Comment by javabster** [comment]
in option 1 the whole box is a clickable link. I could add whatever text you want within the box, but i don't think i could put a link inside because the whole box is technically a link

**Comment by JulesMurphy** [comment]
We probably just need to include an arrow icon or something at the end of the text to make it feel more clickable. Does it have a hover state?

**Comment by javabster** [comment]
Yep!

https://github.com/Qiskit/qiskit-terra/assets/23662430/a2485a05-56e8-4d53-babc-09697c591710
