### ISSUE TITLE
Rename `qiskit.primitives.Estimator` and `qiskit.primitives.Sampler` as `TestEstimator` and `TestSampler` 

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit#10595]
### What should we add?

The reference implementation of Primitives, i.e., `qiskit.primitives.Estimator` and `qiskit.primitives.Sampler`, is based on `Statevector` and it is hard to extend them to support dynamic circuits while `BackendEstimator`, `BackendSampler`, Aer Estimator, and Aer Sampler can support dynamic circuits technically, e.g., #9700.

Moreover, Aer primitives are generally faster than the reference implementation of primitives for the local use case. So, it would be nice to rename and relocate `qiskit.primitives.Estimator` and `qiskit.primitives.Sampler` as something like `TestEstimator` and `TestSampler`, respectively, to be used only for unit tests.

correlated with #4443

**Comment by jakelishman** [comment]
When these were introduced in #7780 it was argued that these two primitives should live in Terra because they were supposed to be used beyond mere testing.  That comes with an expectation that they'll be supported and not so quickly renamed or removed, especially as Qiskit is supposed to become more stable.  For example, #10584 is currently updating the Qiskit/Terra readme to use these objects.  If these objects are to be removed, I think it should be brought up there as well.

**Comment by jaygambetta** [comment]
Since we are moving to these becoming the default way of running quantum circuits I would not do this. My suggestion would be 

Add a check to the Sampler and Estimator to see if it has an extended circuit that includes measurement and if it does bring a error message to the user and suggest that if they want to develop algorithms using advanced simulators that they should either install AER or use the online simulators with more advance runtime environments as the default simulator in qiskit is not for large and complex simulators. 

from qiskit_ibm_rumtime import Estimator 
or 
from qiskit_aer import Estimator 
etc

However, this has pointed out that in #10584 that we should add AER as a provider of runtime for more advance simulation.

**Comment by t-imamichi** [comment]
Jake: When we developed #7780, I didn't know any plan to introduce more implementation for local use such as Backend primitives and Aer primitives. But you are right. We should have named them more carefully. I posted this issue because I thought we need to discuss it before Qiskit gets more stable. Thank you for pointing out #10584 too. I didn't notice it.

Jay: I posted this issue because the name `qiskit.primitives.Estimator(Sampler)` sounds like a default feature though it does not support extended circuits. Thank you for your suggestion to bring messages to suggest Aer or online primitives when extended circuits are received. It makes sense. I will bring your feedback to the Primitive team and discuss it more.

**Comment by ikkoham** [comment]
Just to give some historical context, I have previously proposed to deprecate Estimator/Sampler in Terra and make BackendEstimator/Sampler default since Estimator/Sampler cannot support dynamic circuits, but that has been rejected. Current Estimator/Sampler would be used as a default.

**Comment by Cryoris** [comment]
It's also nice for users to have primitives in Qiskit (Terra) that work out of the box, without needing to install Aer or having to go via the backend primitives. Plus to make the Aer primitives run fast you might need some additional knowledge to set options like `approximation=True`, so the references primitives are great to get started.

**Comment by t-imamichi** [comment]
I close this issue because we need an internal discussion first.
