### ISSUE TITLE
Cannot bind parameters xxx not present in the circuit

### ISSUE THREAD

**Issue by Muzhou-Ma** [Qiskit/qiskit#10715]
### Environment

- **Python version**: 3.10
- **Operating system**:  Windows 11

### What is happening?

I'm trying to bind parameters into my QuantumCircuit:
```
def test_circ(n):
    qc = QuantumCircuit(n)
    a = ParameterVector('a', n)
    for i in range(n):
        qc.rx(a[i], i)
    
    return qc

qc = test_circ(3)
qc.draw()
```

```
     ┌──────────┐
q_0: ┤ Rx(a[0]) ├
     ├──────────┤
q_1: ┤ Rx(a[1]) ├
     ├──────────┤
q_2: ┤ Rx(a[2]) ├
     └──────────┘
```
```
for i in qc.parameters:
    print(i.name)
```

```
a[0]
a[1]
a[2]
```

```
for i in qc.parameters:
    qc.bind_parameters({i.name: np.pi/2})
```
and an error has been raised:

```
File [d:\Anaconda\envs\quantum\lib\site-packages\qiskit\circuit\quantumcircuit.py:2735](file:///D:/Anaconda/envs/quantum/lib/site-packages/qiskit/circuit/quantumcircuit.py:2735), in QuantumCircuit.assign_parameters(self, parameters, inplace)
   2729 params_not_in_circuit = [
   2730     param_key
   2731     for param_key in unrolled_param_dict
   2732     if param_key not in unsorted_parameters
   2733 ]
   2734 if len(params_not_in_circuit) > 0:
-> 2735     raise CircuitError(
   2736         "Cannot bind parameters ({}) not present in the circuit.".format(
   2737             ", ".join(map(str, params_not_in_circuit))
...
   2739     )
   2741 # replace the parameters with a new Parameter ("substitute") or numeric value ("bind")
   2742 for parameter, value in unrolled_param_dict.items():

**CircuitError: 'Cannot bind parameters (a[0]) not present in the circuit.'**
```

what should I do?

### How can we reproduce the issue?

the code above will reproduce this problem

### What should happen?

I suppose values will be bind to the parameters in the circuit

### Any suggestions?

I suppose this are related to #3008 #3014
but I still don't get it.
I'm not familiar with how thind "broadcast" and I don't really understand `why `and` how` `deepcopy` can solve this problem.

**Comment by Muzhou-Ma** [comment]
OHHHHH, I've found that changing my code from:
`qc.bind_parameters({i.name: np.pi/2})`
to:
`qc.bind_parameters({i: np.pi/2})`
might fix it. My bad!

But I'm still confused with `deepcopy`. Can anyone explain it?
Many thanks!

**Comment by Dpbm** [comment]
Hello @Marsmmz, I've done some research and I think that I can answer your question.

By the docs, it's expected to provide a `dictionary mapping Parameter --> value` or an `array with a sequence of values`.

![Bind_parameters.jpg](https://github.com/Qiskit/qiskit/assets/75098594/201fc930-2057-4849-b00f-650b1aea4cc4)

I think that the documentation may be a little bit difficult to understand, since the first thought is to put a `string` there instead of a `Parameter` instance.

However, qiskit uses this approach because it's easier to manage the parameters, once within the parameter class there're some other attributes that control, for example, the index that the parameter has in the circuit.

Because of that, if you check the source code of `parameter.py`, you can see that the `__deepcopy__`, and `__copy__` as well,  return the entire object

![deepcopy.jpg](https://github.com/Qiskit/qiskit/assets/75098594/5295f394-3048-43bf-b4f2-26265993ba2b)

Using some code, you can realize that the pure object and that returned from `deepcopy` are the same

![test.jpg](https://github.com/Qiskit/qiskit/assets/75098594/2ed3fc16-5339-4adf-8540-a18cebadcca3)

So, when you use deepcopy, or not, the code won't raise any error.

![example.jpg](https://github.com/Qiskit/qiskit/assets/75098594/bb237025-de72-48a0-adef-801dc1085411)


I hope it helped you to understand ☺️

**Comment by jakelishman** [comment]
`assign_parameters` and `bind_parameters` take the `Parameter` instance as the key, rather than the name (which is a human-readable version, not a complete UUID).  Your `qc.bind_parameters({i: np.pi/2})` line is the correct call.

**Comment by Muzhou-Ma** [comment]
thanks so much! I've understand it now.
