### ISSUE TITLE
What happened with https://github.com/Qiskit/qiskit-terra ?

### ISSUE THREAD

**Issue by yurivict** [Qiskit/qiskit#10716]
### Environment

There used to be such repository, but now it redirects to https://github.com/Qiskit/qiskit
The Python package [qiskit-terra](https://pypi.org/project/qiskit-terra/) still points there.
Was ```qiskit-terra``` discontinued?
qiskit-finance still depends on qiskit-terra, see [here](https://github.com/qiskit-community/qiskit-finance/blob/main/requirements.txt#L1).

### What is happening?

n/a

### How can we reproduce the issue?

n/a

### What should happen?

n/a

**Comment by diemilio** [comment]
https://github.com/Qiskit/RFCs/blob/master/0011-repo-rename.md

**Comment by 1ucian0** [comment]
> There used to be such repository, but now it redirects to https://github.com/Qiskit/qiskit

The repository `Qiskit/qiskit-terra` was renamed to `Qiskit/qiskit`. All the code that used to live in `Qiskit/qiskit-terra` now lives in `Qiskit/qiskit` and GitHub handles the redirection.

> The Python package [qiskit-terra](https://pypi.org/project/qiskit-terra/) still points there.

Good catch! Fixed in https://github.com/Qiskit/qiskit/pull/10719

> Was qiskit-terra discontinued? qiskit-finance still depends on qiskit-terra, see [here](https://github.com/qiskit-community/qiskit-finance/blob/main/requirements.txt#L1).

No `qiskit-terra` is not discontinued. Qiskit Terra is know renamed as Qiskit. The pip package will continue to be called `qiskit-terra`, at least for the time being.

Feel free to open a discussion in https://github.com/Qiskit/feedback/discussions if you have further questions.
