### ISSUE TITLE
Remove code deprecated in 0.22 (released on October 13, 2022) [pulse]

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#10810]
There is code released 9 month ago that needs to be removed.
 - `qiskit/pulse/utils.py:113`
 - `qiskit/pulse/library/parametric_pulses.py:66`
 - `qiskit/pulse/library/parametric_pulses.py:135`
 - `qiskit/pulse/library/parametric_pulses.py:247`
 - `qiskit/pulse/library/parametric_pulses.py:417`
 - `qiskit/pulse/library/parametric_pulses.py:540`
  
This includes:
- [ ] Remove deprecated code and tests (if they only check the deprecation raise)
- [ ] tag the PR as [`Changelog: Removal`](https://github.com/Qiskit/qiskit/labels/Changelog%3A%20Removal)
- [ ] create a release note in the category `upgrade:`. If you can include an example with an alternative for user to migrate to the new code, as this change might break users code.

Related:
* https://github.com/Qiskit/qiskit/issues/10812
* https://github.com/Qiskit/qiskit/issues/10811
* https://github.com/Qiskit/qiskit/issues/10813

**Comment by Raghav-Bell** [comment]
Please assign this issue to me.

**Comment by 1ucian0** [comment]
Hi @Raghav-Bell , thanks for volunteer! If you don't mind, let's first close some of [the open PRs](https://github.com/Qiskit/qiskit/pulls/Raghav-Bell) and we can leave `good first issue` to new comers. What do you think?

**Comment by Raghav-Bell** [comment]
Yes @1ucian0  I agree.

**Comment by Ak-ash22** [comment]
If this issue still needs attention...Can I be assigned to this? I am new comer.. I wanna try this out. Thank you

**Comment by abhamra** [comment]
I am also interested in contributing as a newcomer, please let me know if this task can be assigned to me

**Comment by 1ucian0** [comment]
@Ak-ash22, assigning you! Thanks!

**Comment by Ak-ash22** [comment]
Hello @1ucian0 ...This is my first time contributing.. kindly help me verify if this is correct :
I have removed all the '@deprecated_func(additional_msg=(..........)) ' and also the line 51 'from qiskit.utils.deprecation import deprecate_func' from the parametric_pulses.py file. 
Also utils.py file doesnt seem to have line 113 in it?. Am I missing something here?

**Comment by 1ucian0** [comment]
The line numbers in the original post might be out of date. I removed `qiskit/pulse/utils.py:113` in https://github.com/Qiskit/qiskit/pull/10881, so no worry about that one. The rest, sounds good.

**Comment by Ak-ash22** [comment]
@1ucian0 I noticed that all the classes in the parametric_pulses.py have been deprecated, so I decided to delete the entire file. Also I noticed a bug in the related test.... in the qiskit/test/python/pulse/test_pulse_lib.py, there is a test class named TestParametricPulses but it calls all the Gaussian, Constant etc waveforms from the symbolic_pulses.py and not from the paramteric_pulses.py. So I changed the name of the test class to TestSymbolicPulses(..). Also I made sure that there is no test case for symbolic pulses, just to be sure I am not duplicating it.
Let me know if these changes are ok?! so that I can do tox tests and move forward with submitting a PR.
