### ISSUE TITLE
Optimization level=0 fails on Seattle

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#10864]
### Environment

- **Qiskit Terra version**: latest
- **Python version**: 
- **Operating system**: 

### What is happening?

```python
backend = provider.get_backend('ibm_seattle')
circ = transpile(EfficientSU2(400, entanglement='circular'),
                          backend, optimization_level=0)
```
fails with

TranspilerError: 'Chosen layout is not valid for the target disjoint connectivity'

### How can we reproduce the issue?

run above

### What should happen?

It should work

### Any suggestions?

I guess this is because the trivial layout is disjoint.  There should be some workaround like a graph search that equals the trivial layout in the usual case

**Comment by mtreinish** [comment]
This is expected behavior. At the time we added support for disjoint connectivity graphs to the transpiler in #9840 it was a discussion point around how to handle level 0. The consensus at the time was that expectation for level 0 is to always use a trivial layout by default as the expected use case is for characterization experiments or hardware aware circuits, and in the case that a circuit was not routable because it required connectivity between disjoint connected components we should just error. This was recently brought up again in #10731 and we changed the error message to be a bit more clear in #10733. To use level 0 which isn't hardware aware on a disjoint backend you can just do `transpile(..., layout_method="sabre")` to explicitly say you want to use a heuristic layout.

**Comment by nonhermitian** [comment]
This can be closed
