### ISSUE TITLE
QASM output for multiple R gates

### ISSUE THREAD

**Issue by christian512** [Qiskit/qiskit#11017]
### Environment

- **Qiskit Terra version**: 0.25.2.1
- **Python version**: 3.11.5
- **Operating system**: Fedora

### What is happening?

I create a `QuantumCircuit` from a `qasm` string that contains multiple `R` gates. E.g.:

```
OPENQASM 2.0;
include "qelib1.inc";
gate r(param0,param1) q0 { u3(param0,param1 - pi/2,pi/2 - 1.0*param1) q0; }
qreg q[2];
r(0.1,0.1) q[0];
r(0.5,0.5) q[1];
```

Generating the `qasm` string from the previously generated `QuantumCircuit` does result in the `R` gates being defined multiple times: 

```
OPENQASM 2.0;
include "qelib1.inc";
gate r(param0,param1) q0 { u3(0.1,-1.4707963267948965,1.4707963267948965) q0; }
gate r_140480215738000(param0,param1) q0 { u3(0.5,-1.0707963267948966,1.0707963267948966) q0; }
qreg q[2];
r(0.1,0.1) q[0];
r_140480215738000(0.5,0.5) q[1];
```

### How can we reproduce the issue?

```
qc = QuantumCircuit(2)
qc.r(0.1,0.1,0)
qc.r(0.5,0.5,1)

qc2 = QuantumCircuit.from_qasm_str(qc.qasm())
qc2.qasm()
``

### What should happen?

I would expect the `qasm` input and output to a `QuantumCircuit` to be the same. Especially, if there are no changes applied to the object.

### Any suggestions?

_No response_

**Comment by jakelishman** [comment]
This is in principle a duplicate of #5082, which requires a larger rework of our data model to handle (which we are working on, I promise! - it's just a very very big change), but the reason you only see this after a re-import from the OQ2 string is because Qiskit can't know for certain that it's safe for it to use its built-in `RGate` to represent the `gate r` statement.

We're currently [reworking how we'll define header files for OpenQASM 2](https://github.com/Qiskit/qiskit/issues/10737), which will make this easier, but in the meantime, a direct workaround is to replace the legacy `QuantumCircuit.from_qasm_str` with `qiskit.qasm2.loads`, which is far more configurable.  If you do this:
```python
from qiskit import qasm2
from qiskit.circuit.library import RGate

prog = """
OPENQASM 2.0;
include "qelib1.inc";
gate r(param0,param1) q0 { u3(param0,param1 - pi/2,pi/2 - 1.0*param1) q0; }
qreg q[2];
r(0.1,0.1) q[0];
r(0.5,0.5) q[1];
"""

custom_instructions = list(qasm2.LEGACY_CUSTOM_INSTRUCTIONS)
custom_instructions.append(qasm2.CustomInstruction("r", 2, 1, RGate))

qc = qasm2.loads(prog, custom_instructions=custom_instructions)
print(qasm2.dumps(qc))
```
I think you'll get what you expect.

*edit*: just modified the code block - I'd flipped the arguments in `CustomInstruction` by accident.

**Comment by jakelishman** [comment]
The gist of #10737 (linked above) is that we're going to start exposing new header files called things like `qiskit/v1.qasm`, and that will include definitions of _all_ of Qiskit's standard gates, not just the legacy ones that kind of got mashed into Qiskit's not-very-accurate version of `qelib1.inc` (see #4312).  That will let us safely know when we're importing OQ2 that's targetted at our standard gates, without making assumptions about user-defined gates.

**Comment by christian512** [comment]
Thanks @jakelishman for the detailed response! 
Using `qasm2.loads()` solved my issue. Looking forward to the new implementation.

I close this issue, since it is a duplicate of #5082.
