### ISSUE TITLE
Deprecate Qobj in unitary_simulator.py

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#11046]
> I also just realized that `qiskit.providers.basicaer.UnitarySimulatorPy.run()` (https://github.com/Qiskit/qiskit/blob/main/qiskit/providers/basicaer/unitary_simulator.py#L206) never deprecated a Qobj input and will still support it while the qasm simulator and statevector simulator will not. I still think we should move forward with your PR, but it's something we'll want to clean up in a subsequent PR.

_Originally posted by @mtreinish in https://github.com/Qiskit/qiskit/pull/10872#pullrequestreview-1685997898_

**Comment by rupeshknn** [comment]
Hi, I'd like to work on this. the description isn't very clear, though, could you help me with what needs to be done? Should I just deprecate Qobj input or remove this functionality?

**Comment by rupeshknn** [comment]
When a `QasmQobj` is supplied to `QasmSimulatorPy.run` or `StatevectorSimulatorPy.run`, the error raised is:
```python
QiskitError: 'bad input to assemble() function; must be either circuits or schedules'
```

And when a  `QasmQobj` is supplied to `QasmSimulatorPy.run`, it complains that there's no `n_qubits` property for `QasmQobj` rather than clearly stating that only circuits are supported. (as the `assemble` call is tucked under a conditional)

Since a `Qobj` input cannot be used anyway, I think it's better to **remove** `Qobj` support directly rather than deprecate it and remove it in a later release. What do you think @1ucian0 @mtreinish?

**Comment by rupeshknn** [comment]
Based on the conversation [here](https://qiskit.slack.com/archives/C024ELK40TW/p1701877287222499) with @1ucian0 I'll start with a deprecation PR to `stable\0.46` and once that's done, I'll do a removal PR to `main`.
