### ISSUE TITLE
Documentation: some class docstring have broken links in qiskit.pulse API doc

### ISSUE THREAD

**Issue by grossardt** [Qiskit/qiskit#11239]
In the API Documentation for [qiskit.pulse](https://docs.quantum-computing.ibm.com/api/qiskit/pulse), some classes have broken links.

E.g. under the section [Parametric Pulse Representation](https://docs.quantum-computing.ibm.com/api/qiskit/pulse#parametric-pulse-representation) links to classes `qiskit.pulse.library.Constant`, `qiskit.pulse.library.Drag`, or `qiskit.pulse.library.Gaussian` lead to 'page not found'. In contrast, links to `qiskit.pulse.library.GaussianSquare` or `qiskit.pulse.library.GaussianDeriv` work.

I tried to understand the difference between those docstrings in `symbolic_pulses.py` but I cannot see an obvious reason why some work and others don't.

**Comment by Raghav-Bell** [comment]
For new documentation related issues please raise issue in [documentation repo](https://github.com/Qiskit/documentation).

**Comment by jakelishman** [comment]
There's a few moving parts here, and the deployment to `docs.quantum-computing.ibm.com` isn't handled by this repo (see https://github.com/Qiskit/documentation), but the problem is definitely somewhere here.  Those particular classes used to have overrides in the API-documentation generation: https://github.com/Qiskit/qiskit/blob/87fcd71e8586fb82e8d55e19d2d76d5821d2f94c/docs/conf.py#L167-L182

The configuration of those has probably rotted as part of some other rearrangements of documentation efforts - maybe it was #10455, #10471 or some change to the pulse module itself (which I don't have so clearly tracked in my head).  We can try and track down what's going on with that and get those fixed, thanks for the report.

@Raghav-Bell: this issue is related to API documentation, and it is correct to raise it here.

**Comment by Raghav-Bell** [comment]
@jakelishman Yes, you are correct as this issue is in previous version too [old docs](https://qiskit.org/documentation/apidoc/pulse.html).

**Comment by arnaucasau** [comment]
Hi! Today, I have also seen this issue when setting the link checker for the documentation. [Here](https://github.com/Qiskit/documentation/actions/runs/6868139157/job/18677991413?pr=349) you can see how those links are broken, and also other links we can find in `autosummary_filename_map`. I'm going to look into it as well.

**Comment by arnaucasau** [comment]
Hello! it seems like the problem with those classes was caused by the Cloudflare redirect configuration. In there we were redirecting every link in `qiskit.org/documentation/stubs/` to the same link but removing the last part before .html if the previous component started with uppercase. This was the case for all the links in the `autosummary_filename_map`.

For example in the link `https://qiskit.org/documentation/stubs/qiskit.pulse.library.Constant_class.rst.html` we were removing the `.rst` part making the pages inaccessible.

I created a PR in there to fix the problem, and it should be fixed soon. Thanks @grossardt for opening the issue and @jakelishman for the information!

**Comment by jakelishman** [comment]
Thanks Arnau!  Would you be able to let us know on this issue / close it if you have permission once the redirects are fixed?

**Comment by arnaucasau** [comment]
Yes, of course! I can't close the issue, but I'll let you know when they are fixed 👍

**Comment by arnaucasau** [comment]
Hi @jakelishman. The issue can be closed! All the broken links in `qiskit.pulse` have been fixed :) You can see that the docs have been added to qiskit/documentation through this [PR](https://github.com/Qiskit/documentation/pull/417), and it's already working on the [website](https://docs.quantum.ibm.com/api/qiskit/pulse#parametric-pulse-representation).

**Comment by jakelishman** [comment]
Super, thanks Arnau!
