### ISSUE TITLE
Broken links in API topics

### ISSUE THREAD

**Issue by beckykd** [Qiskit/qiskit#11481]
### Environment

N/A

### What is happening?

Broken link report from @lerongil

Getting links from: https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit#quantumcircuit
├─BROKEN─ https://docs.quantum.ibm.com/api/qiskit/qiskit.org/documentation/tutorials/circuits/3_summary_of_quantum_operations (HTTP_404)
Finished! 1418 links found. 1354 excluded. 1 broken.
​
Getting links from: https://docs.quantum.ibm.com/api/qiskit-ibm-runtime/qiskit_ibm_runtime.QiskitRuntimeService
├─BROKEN─ https://auth.quantum-computing.ibm.com/api (HTTP_404)
├─BROKEN─ https://auth.quantum-computing.ibm.com/api (HTTP_404)
Finished! 118 links found. 116 excluded. 2 broken.
​
Getting links from: https://docs.quantum.ibm.com/api/qiskit-ibm-provider/qiskit_ibm_provider.IBMProvider
├─BROKEN─ https://auth.quantum-computing.ibm.com/api (HTTP_404)
├─BROKEN─ https://auth.quantum-computing.ibm.com/api (HTTP_404)
├─BROKEN─ https://auth.quantum-computing.ibm.com/api (HTTP_404)
Finished! 97 links found. 94 excluded. 3 broken.

### How can we reproduce the issue?

check links

### What should happen?

Links should be updated or removed

**Comment by jakelishman** [comment]
The top of this list was fixed in #11294, which is the only item here that's part of this repo. The others come from https://github.com/Qiskit/qiskit-ibm-runtime and https://github.com/Qiskit/qiskit-ibm-provider respectively.

I believe everything that can be solved here on Terra is already fixed so I'll close the issue, but please feel free to re-open, make a new one if that's not the case.
