### ISSUE TITLE
contributing documentation

### ISSUE THREAD

**Issue by amaloney** [Qiskit/qiskit#11507]
### What should we add?

Getting a functioning dev environment has steps not outlined in the current [CONTRIBUTING.md](https://github.com/Qiskit/qiskit/blob/main/CONTRIBUTING.md) documentation. As an example, the section on using conda is not complete as there is no environment file for conda in the repo, and there are dependencies that will be missed if a user follows the current documentation as is.

I would also like to point out that there are steps in the project's `Makefile` that could help speed up starting development on the project, and should be highlighted in the contributing document. I personally glazed over the rules in the Makefile when creating my first PR, and probably should not have done so as there are good steps that I should have done before creating it. Some of the steps in the makefile, e.g. linting and formatting, could be automated by `pre-commit` for local development. If the community is interested in using `pre-commit`, I'd be happy to add those to the dev process, and the creation of its documentation. Let me know if y'all would like one or the other, or both items discussed in this request.

1. Update the `CONTRIBUTING.md` document with more discussions on how to build a working dev environment.
1. Add `pre-commit` as a dev dependency and document its use.

**Comment by jakelishman** [comment]
Thanks for the report - some of our dev-env documentation may have got a bit lost in a recent transition of where the Qiskit documentation lives, and some of it may be out of date, so it's good to be fixed up.  We should be careful about overloading it with too many permutations of things, though - it's already probably too long, and people using non-standard tooling like `conda` can consult its own documentation.

I don't think a Conda environment file is necessary; we use `tox` for dev-tooling isolation, along with requirements files in the standard built-in format (pip requirements files, like `requirements-dev.txt`).  [The lint suite is run by `tox -e lint`, as discussed in the contributing guide](https://github.com/Qiskit/qiskit/blob/main/CONTRIBUTING.md#style-and-lint), and [the local API docs preview is built with `tox -e docs`](https://github.com/Qiskit/qiskit/blob/main/CONTRIBUTING.md#building-api-docs-locally).  There's no need for somebody getting started to install the tools manually; all you need is to build the package from source, which is done by the standard `pip install -e .`, with a Rust compiler available.

I'm actually a bit surprised that the Makefile commands still work - I didn't think it had been significantly maintained for years despite a lot changing in how we lint, run CI, and everything else.  I'd largely forgotten it existed.

You're quite welcome to use `pre-commit` locally if you desire, but beware that `pylint` is rather slow (runtime of minutes) and unsuited to it. I personally have not been too convinced by `pre-commit`; it's one more of a litany of things to teach new contributors to install, it slows down committing so gets in the way of "commit-then-rebase" workflows, and we have to test everything it would check in CI anyway because it's not guaranteed to run.

**Comment by amaloney** [comment]
Understood. I'll continue to read the code base more and determine where my misunderstanding came from while building a dev environment. If there is anything I think is relevant by breaking down the process again, I'll make a different issue with a PR.

I'm going to close this issue in favor of the discussion in #11504
