### ISSUE TITLE
PanicException: called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }

### ISSUE THREAD

**Issue by Superhsl** [Qiskit/qiskit#11561]
### Environment

- **Qiskit Terra version**: qiskit 0.44.1
- **Python version**: 3.9
- **Operating system**: linux

### What is happening?

I'm simply trying to generate a QuantumCircuit object from different QASM files. Why can some files be generated successfully while others result in an error?

### How can we reproduce the issue?

'''from qiskit import QuantumCircuit
qc = QuantumCircuit.from_qasm_file("ae_indep_qiskit_69.qasm")'''

### What should happen?

generate a QuantumCircuit object

**Comment by jakelishman** [comment]
Please could you try and cut down your `ae_indep_qiskit_69.qasm` file to be as small as you can while still showing the error, and then share it here?

**Comment by DSGuala** [comment]
I ran into the same error. It can be reproduced with this QASM string:
```
OPENQASM 2.0;
include "qelib1.inc";
qreg eval[67];
qreg q[1];
creg meas[68];
u(-21779497794157969408*pi,0,0) q[0];
```

**Comment by jakelishman** [comment]
Sorry for the delay in response - I was off on holiday.  Thanks a lot for the reproducer - that's very helpful and I can see where the problem is now.

Out of curiosity, how did you end up with an OpenQASM 2 file with such a huge-magnitude rotation in it?  For what it's worth, there's a fair chance that if that number started off as a float, then the output has been rendered totally incorrect by running out of floating-point precision - that integer has 65 binary digits, which is far more than double-precision floating point can handle.  (It's also more than a 64-bit integer can handle, which is why the OQ2 importer is choking on it.)

**Comment by DSGuala** [comment]
Thanks for taking a look!
>how did you end up with an OpenQASM 2 file with such a huge-magnitude rotation in it

Short answer: I downloaded it from the [MQTBench dataset](https://www.cda.cit.tum.de/mqtbench/)

Long (speculative) answer: 
- The original authors used `qiskit.circuit.library.PhaseEstimation` on many estimation qubits: 65 qubits and more. 
- This translated to applying some controlled rotation $2^{65}$ times. Let's say a $\pi$ rotation for example.
- Somewhere along the pipeline Qiskit combined the $2^{65}$ gates into a single one by adding them up.
- Result: we get a rotation with angle $2^{65} \pi = 1.16e20$ which has around 67 binary digits. :boom: 

:heavy_plus_sign: :one: , sounds likely that the final number is nonsense :thinking: I will take a look

**Comment by jakelishman** [comment]
I've made #12140 which should hopefully fix these problems, though the potential issue of loss-of-precision in the generation of the OpenQASM 2 file will of course still be there.
