### ISSUE TITLE
Circuit parameters are not cleared via `global_phase` setter

### ISSUE THREAD

**Issue by chriseclectic** [Qiskit/qiskit#11640]
### Environment

- **Qiskit Terra version**: 1.0
- **Python version**: 3.11
- **Operating system**: MacOS

### What is happening?

I've run into a bug when working with parameteric circuits and think I have tracked it down to the `global_phase` setter. The issue is that if a circuit has a parametric global phase, and then this is set to a numeric value (in my case 0), while the circuit parameter table is updated to remove the phase parameter, the `circuit.parameters` is not.

### How can we reproduce the issue?

```python
# Make a circuit with parametric global phase
qc = QuantumCircuit(1)
qc.global_phase = Parameter("a")

# Print parameters and parameter table
print(qc.parameters)
print(qc._parameter_table)

ParameterView([Parameter(a)])
ParameterTable({Parameter(a): ParameterReferences([(<global-phase sentinel>, None)])})
```

```python
# Now zero phase and print again
qc.global_phase = 0
print(qc.parameters)
print(qc._parameter_table)

ParameterView([Parameter(a)])
ParameterTable({})
```

### What should happen?

I would expect after setting `globla_phase = 0` `Parameter("a")` should no longer appear in `circuit.parameters`, since it is not present in the circuit any longer.

### Any suggestions?

Circuit.parameters is cached the first time it is called, so likely the globla_phase setter in the first case should also clear the cache by setting `self._parameters = None` when re-assigning a parametric circuit global phase.

**Comment by chriseclectic** [comment]
This issue seems to be present in early versions too (<=0.46), though in those cases the parameter doesn't seem to appear in the parameter table mapping, and the two cases above both print
```
ParameterView([Parameter(a)])
ParameterTable({})
```
when the second should print
```
ParameterView([])
ParameterTable({})
```

**Comment by jakelishman** [comment]
Yeah, looks like a straight bug in the `global_phase` setter thanks - it touches the `ParameterTable` but doesn't invalidate the cached value.

**Comment by jakelishman** [comment]
Oh, I missed that second comment too - yeah, prior to Qiskit 1.0 the global phase wasn't tracked in the `ParameterTable` at all, and various places that accessed the parameters had to manually check if `global_phase` was parametric or not.  There's probably quite a few places around that got it wrong - I think I've found at various times that `remove_final_measurements`, `compose`, `assign_parameters` and `copy_empty_like` have all had special handling for it, some more successfully than others.  When I added `QuantumCircuit.get_parameter`, it was going to be _one more_ place that would easily get desynced, so I held it on (an attempt to) fix the tech debt and put `global_phase` into the `ParameterTable` properly (#11428).

That PR caused a few places that previously had buggy handling of parametric global phase to suddenly start noisily erroring, whereas previously they'd silently been doing the wrong thing and it hadn't been noticed because checking the global phase is relatively uncommon.

At any rate, #11641 should fix this missing cache invalidation - thanks for the report.
