### ISSUE TITLE
CPhaseGate parameter name mismatch in API docs

### ISSUE THREAD

**Issue by marvin-richter** [Qiskit/qiskit#11809]
### URL to the relevant documentation

https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.CPhaseGate

### Select all that apply

- [X] typo
- [ ] code bug
- [ ] out-of-date content
- [ ] broken link
- [ ] other

### Describe the fix.

Mismatch between theta as the parameter of the controlled phase-gate and $\lambda$ everywhere else on the page.

**Comment by Eric-Arellano** [comment]
Thanks, Marvin! I'm transferring this to the qiskit/qiskit repository because API doc changes need to happen there.

Would you be interested in fixing this? It looks like changing the docstring in https://github.com/Qiskit/qiskit/blob/9184907e1cc9b8563186a559d2e446518bbe8fac/qiskit/circuit/library/standard_gates/p.py#L159.

**Comment by cameron-d28** [comment]
@Eric-Arellano for this issue would the solution be to change 1) the parameter or 2) the notation in the representation. i would assume change 2 as it would keep the parameter for many of the gates as theta rather than having theta be confused with lamda in the params.

**Comment by cameron-d28** [comment]
could i also please be assigned this?
