### ISSUE TITLE
qiskit.provider.back_compat.convert_to_target doesn't add control flow instructions to the target

### ISSUE THREAD

**Issue by blakejohnson** [Qiskit/qiskit#11872]
### Environment

- **Qiskit version**: 1.0
- **Python version**: 3.11.7
- **Operating system**: macOS 13.6

### What is happening?

`convert_to_target` doesn't populate the target with control flow instructions.

### How can we reproduce the issue?

Example using an IBM backend, but the problem is not due to the `qiskit_ibm_runtime`.

```python
from qiskit_ibm_runtime import QiskitRuntimeService

# pick any Eagle backend
backend = service.get_backend("ibm_brisbane")

set(instr.name for instr, qargs in backend.target.instructions)
```

will be missing `if_else`, `for_loop`, and `switch_case`. 

Following the chain, you see that `backend.target` is calling:
```python
convert_to_target(
                configuration=self._configuration,
                properties=self._properties,
                defaults=self._defaults,
            )
```

### What should happen?

The control flow operations should be in the target instructions.

### Any suggestions?

The issue seems to be that `convert_to_target` [populates a value](https://github.com/Qiskit/qiskit/blob/main/qiskit/providers/backend_compat.py#L94) `all_instructions` from `configuration.basis_gates`. And then iterates over `all_instructions` to [pick up control flow](https://github.com/Qiskit/qiskit/blob/main/qiskit/providers/backend_compat.py#L275). However, control flow instructions are not in basis gates. Instead, they are found in `supported_instructions`. Therefore, I think the change that is required is to populate `all_instructions` from `supported_instructions` rather than `basis_gates`.

**Comment by jakelishman** [comment]
We can switch this over to use `supported_instructions`, though that is a behavioural change of the function.

We'll need to have a fallback to `basis_gates`, though, because `supported_instructions` is an optional field on `BackendV1::BackendConfiguration`, so not all implementors will necessarily have it.  I think we might also need to define what we do if `supported_instructions` is not a superset of `basis_gates`; do we prefer `supported_instructions`, or use the union of the two?

**Comment by 1ucian0** [comment]
I think the union of the two makes more sense.

**Comment by blakejohnson** [comment]
I concur that union of the two makes the most sense.

**Comment by mtreinish** [comment]
The reason supported instructions isn't typically considered by default is historically the api response from IBM included a lot of instructions which had no context in the circuit model or for the transpiler in that field. In the `BackendV1`  path the transpiler ignores `supported_instructions` field as well and only looks at `basis_gates` (this is why things like measure and reset are in the basis gates list)

A straight union won't actually work in the general case for the converter as it's possible to end up with a backend that has an inconsistent set of gates which won't be interpreted well. For a concrete example you can look at the snapshots of older backends like:

https://github.com/Qiskit/qiskit-ibm-runtime/blob/main/qiskit_ibm_runtime/fake_provider/backends/hanoi/conf_hanoi.json

the supported instructions list there is:

```python
["rz", "play", "measure", "delay", "acquire", "sx", "cx", "reset", "x", "shiftf", "u1", "u3", "u2", "setf", "id"]
```

while the basis gates were:

```python
["id", "rz", "sx", "x", "cx", "reset"]
```

Doing a union would result in instructions that would trigger a warning but ultimately get ignored for the pulse things like `play` or `shiftf`. But the bigger concern are things like `u1`, `u2`, and `u3` (which are in the list because they were still defined pulse calibrations on the backend despite not being basis gates anymore). Doing a union of these lists would result in the output target having `u1`, `u2`, and `u3` being globally defined ideal gates (like what a simulator would put in the target). This potential inconsistency is a major issue with the backend v1 models and is larger than just this specific example. We need to take care with how we extend things here as we need the converter to support the general `BackendV1`  models not just the current IBM usage of the interface. 

That all being said I think the best path forward here is to look specifically for the presence of control flow instructions in the `supported_instructions` field and only add those to the target if they're present. There are only 4 of them: https://github.com/Qiskit/qiskit/blob/main/qiskit/circuit/controlflow/__init__.py#L27 and we can just do the intersection of `configuration.supported_instructions` and that frozen set. IIRC this is actually what the `qiskit-ibm-provider` used to do when it had it's own internal version of the `convert_to_target` function.

**Comment by blakejohnson** [comment]
Special casing control flow is probably fine for now.
