### ISSUE TITLE
When i use quantum lab  by default it import some libraries from qiskit import QuantumCircuit, transpile from qiskit.tools.jupyter import * from qiskit.visualization import * from ibm_quantum_widgets import *.When i run this getting error Traceback (most recent call last):   Cell In[1], line 3     from qiskit.tools.jupyter import * ModuleNotFoundError: No module named 'qiskit.tools'.help me to solve it

### ISSUE THREAD

**Issue by rajaniharsha** [Qiskit/qiskit#11898]
### Environment

- **Qiskit version**: v1.0.0
- **Python version**: default with IBM Quantum Lab
- **Operating system**: 10

### What is happening?

When i use quantum lab  by default it import some libraries from qiskit import QuantumCircuit, transpile from qiskit.tools.jupyter import * from qiskit.visualization import * from ibm_quantum_widgets import *.
When i run this getting error 
Traceback (most recent call last):   Cell In[1], line 3     from qiskit.tools.jupyter import * ModuleNotFoundError: No module named 'qiskit.tools'.
help me to solve it

### How can we reproduce the issue?

# Importing standard Qiskit libraries
from qiskit import QuantumCircuit, transpile
from qiskit.tools.jupyter import *
from qiskit.visualization import *
from ibm_quantum_widgets import *

# qiskit-ibmq-provider has been deprecated.
# Please see the Migration Guides in https://ibm.biz/provider_migration_guide for more detail.
from qiskit_ibm_runtime import QiskitRuntimeService, Sampler, Estimator, Session, Options

# Loading your IBM Quantum account(s)
service = QiskitRuntimeService(channel="ibm_quantum")

# Invoke a primitive. For more details see https://docs.quantum.ibm.com/run/primitives
# result = Sampler().run(circuits).result()

### What should happen?

it has to execute the all the libraries

**Comment by 1ucian0** [comment]
Thanks for the headsup! We are forwarding this to IBM Quantum Lab team.

The reason for the issue is that cell was not updated to Qiskit 1.0, released on Feb 15th. You have two options at this point:
 * force an installation of a Qiskit compatible version: You can install arbitrary versions of Qiskit in your environment, for example `!pip install qiskit==0.46.0`.
 * adapt your code to run with the current version in the environment: In the case this case, you can remove the imports that are failing if you are not using them.
