### ISSUE TITLE
OpenQASM3 dumper does not work with repeated conditionals

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#11936]
### Environment

- **Qiskit version**: 1.1.0.dev0+197e78c
- **Python version**: 3.11.7
- **Operating system**: MacOS

### What is happening?

While I was trying to reproduce https://github.com/Qiskit/qiskit/issues/11935 (and succeeding), I noticed that the OpenQASM3  dumper has the same problem. It seems that is not working with repeated conditionals 

### How can we reproduce the issue?

```python
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister
from qiskit.circuit.library.standard_gates import CXGate

qr = QuantumRegister(2, name='qr')
cr = ClassicalRegister(2, name='cr')
qc = QuantumCircuit(qr, cr, name='qc')
qc.append(CXGate().c_if(cr, 0).repeat(1), qargs=qr)

from qiskit.qasm3 import dumps

print(dumps(qc))
```
```
KeyError: "'ClassicalRegister(2, 'cr')' is not defined in the current context"
```

### What should happen?

Notice that the example works with OpenQASM 2 dumper:

```python
from qiskit.qasm2 import dumps

print(dumps(qc))
```
```
OPENQASM 2.0;
include "qelib1.inc";
gate cx_1 q0,q1 { if(cr==0) cx q0,q1; }
qreg qr[2];
creg cr[2];
cx_1 qr[0],qr[1];
```

**Comment by jakelishman** [comment]
The problem here is happening some time before we get to the OQ2 and OQ3 dumpers (note that the OQ2 dumper's output is invalid OQ2).  Looks like a `Gate` with a condition is being allowed to be used in some other `Gate` object, but classical conditions aren't unitary so that should have been forbidden.  The error's more likely in `Gate.repeat` than the dumpers, here.
