### ISSUE TITLE
Add MCRX, MCRY and MCRZ gates to the circuit library

### ISSUE THREAD

**Issue by ShellyGarion** [Qiskit/qiskit#12048]
### What should we add?

Currently we have the methods [`mcrx`](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit#mcrx), [`mcry`](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit#mcry) and [`mcrz`](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit#mcrz) in the [QuantumCircuit](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit) class, but they don't appear in the [circuit library](https://docs.quantum.ibm.com/api/qiskit/circuit_library). 
I would suggest to add them to the circuit library as the other multi-controlled gates.

In addition, in order to make a unified API as the other multi-controlled gates, these gates should include the following:

1. The angles should be of type `ParameterValueType` (not only `float`).
2. Add `ctrl_state` parameter (like in [`MCXGate`](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.MCXGate)).
3. The `control` method of the `rx`, `ry` and `rz` gates, should call the `MCRX`, `MCRY` or `MCRZ` gates respectively (if there are more than two qubits)

**Comment by ShellyGarion** [comment]
Following the discussion in https://github.com/Qiskit/qiskit/issues/12863#issuecomment-2260278687, I'll close this issue (and transfer some tasks to #12863)

**Comment by ShellyGarion** [comment]
Following the discussion in https://github.com/Qiskit/qiskit/issues/12863#issuecomment-2260278687, I'll close this issue (and transfer some tasks to #12863)

**Comment by ghost** [comment]
Analysis: MCRX, MCRY and MCRZ Gates Feature Request
This GitHub issue (#12048) represents a completed feature request to enhance Qiskit's circuit library with multi-controlled rotation gates. Here's a comprehensive analysis:

Issue Summary
Status: ✅ Closed as Completed (July 31, 2024)
Requestor: ShellyGarion (Qiskit team member)
Priority: Circuit library enhancement

Problem Statement
The issue identified an API inconsistency in Qiskit's gate library:

Existing: mcrx(), mcry(), mcrz() methods existed in QuantumCircuit class

Missing: Corresponding gate objects (MCRXGate, MCRYGate, MCRZGate) in the circuit library

Inconsistency: Other multi-controlled gates (like MCXGate) had both methods and library objects

Requested Enhancements
1. Circuit Library Integration
Add proper gate classes to match the existing pattern:

python
# Before: Only circuit methods existed
qc.mcrx(angle, control_qubits, target_qubit)

# After: Both methods and library gates
from qiskit.circuit.library import MCRXGate
gate = MCRXGate(angle, num_ctrl_qubits=3)
2. Enhanced Parameter Support
python
# Before: Limited to float angles
qc.mcrx(3.14159, [0,1,2], 3)

# After: Support ParameterValueType
from qiskit.circuit import Parameter
theta = Parameter('θ')
qc.mcrx(theta, [0,1,2], 3)  # Symbolic parameters
3. Control State Specification
python
# Enhanced API similar to MCXGate
MCRXGate(angle, num_ctrl_qubits=3, ctrl_state='101')  # Mixed control states
4. Unified Control Method Integration
python
# Before: Manual multi-controlled gate creation
# After: Automatic promotion for complex controls
rx_gate = RXGate(angle)
multi_controlled_rx = rx_gate.control(num_ctrl_qubits=4)  # Auto-creates MCRXGate
Implementation Impact
Benefits Achieved
API Consistency: Multi-controlled rotation gates now follow the same pattern as other multi-controlled gates

Enhanced Flexibility: Support for parameterized angles and mixed control states

Better Integration: Seamless interaction with Qiskit's parameter binding and optimization systems

Improved Synthesis: More efficient decomposition strategies for multi-controlled rotations

Use Cases Enabled
Quantum Algorithms: More efficient implementation of conditional rotations in algorithms like QAOA

Parameterized Circuits: Better support for variational quantum algorithms with symbolic parameters

Hardware Optimization: Improved transpilation for devices with specific multi-controlled gate capabilities

Related Issues and Context
The issue was connected to broader circuit library organization efforts:

#1[2](https://github.com/Qiskit/qiskit/issues/12048)135: Controlled UGate parameter handling

#12289: Implementation pull request

#1286[3](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.RZGate): Multi-controlled gate synthesis library organization

Current Status
✅ Resolution: The issue was successfully implemented and closed as part of Qiskit's ongoing circuit library improvements. The implementation provides:

Consistent API design across all multi-controlled gates

Enhanced parameter support for quantum algorithm development

Better integration with Qiskit's transpilation and optimization pipeline

Improved performance for multi-controlled rotation operations

This enhancement represents a significant improvement in Qiskit's usability for quantum algorithm developers working with complex multi-controlled operations.
