### ISSUE TITLE
import ibm_cloud  token with error                   

### ISSUE THREAD

**Issue by IBMjason** [Qiskit/qiskit#12433]
### What should we add?

[deleted image]

**Comment by jakelishman** [comment]
I highly suggest you regenerate your token _immediately_, as you've leaked it in its entirety.

Your problem is that the object is called `QiskitRuntimeService`, not `qiskit_runtime_service`.  The GitHub repository for that package is also here: https://github.com/Qiskit/qiskit-ibm-runtime, but you might find [the documentation on getting started with the runtime service useful](https://docs.quantum.ibm.com/run/primitives-get-started).

**Comment by IBMjason** [comment]
@jakelishman Thanks. I corrected, but still meet this error. Please kindly help check.

![Xnip2024-05-17_23-39-57](https://github.com/Qiskit/qiskit/assets/169342969/7280355e-a993-4571-882d-81d23af67539)

**Comment by jakelishman** [comment]
Please read the getting started documentation.
