### ISSUE TITLE
Transpiler gives wrong result

### ISSUE THREAD

**Issue by BankNatchapol** [Qiskit/qiskit#12440]
### Environment

- **Qiskit version**: 1.1.0 
- **Python version**:  3.10.12
- **Operating system**:  Google Colab 

### What is happening?

Transpiler optimization level 2, 3 give wrong results.

### How can we reproduce the issue?

```
with open('aaaa.qpy', 'rb') as fd:
    aaaa = qpy.load(fd)[0]

bbbb = transpile(aaaa, basis_gates=['z', 't', 'x', 'y', 'cx', 'tdg', 's, sdg', 'h', 'rz'], optimization_level=2)

if not Statevector.from_instruction(aaaa).equiv(Statevector.from_instruction(bbbb)):
  raise Exception('State Vector not equal')
```
Ill attach zip file of aaa.qpy
[aaaa.zip](https://github.com/Qiskit/qiskit/files/15360427/aaaa.zip)

### What should happen?

The state vector should be the same.

**Comment by mtreinish** [comment]
Your input circuit has swap gates in it. At optimization level 2 (and 3) the  transpiler is able to optimize those gate away by just permuting the virtual qubits by the `ElidePermutations` pass (which was introduced in 1.1.0). This is tracked as a permutation in the [layout attribute](https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.QuantumCircuit#calibrations) `QuantumCircuit.layout`. When you convert the output circuit to an instruction with `from_instruction` this layout information is discarded and the statevector evolution isn't factoring in the permutation and that's why it evaluates false. The transpiler maintains unitary equivalence of the circuit up to that permutation (for example see: https://docs.quantum.ibm.com/api/qiskit/circuit#simulating-circuits)

You can use `Operator.from_circuit()` to construct a unitary of the circuit that reverses that permutation for example:

```python
from qiskit.quantum_info import Operator

bbbb_unitary = Operator.from_circuit(bbbb)
aaaa_unitary = Operator.from_circuit(aaaa)
assert bbbb_unitary == aaaa_unitary
```
If you want to do this with a statevector you can too:

```python
from qiskit.circuit import QuantumCircuit
aaaa_sv = Statevector.from_instruction(aaaa)
bbbb_sv = Statevector(QuantumCircuit(bbbb.num_qubits))
bbbb_sv = bbbb_sv.evolve(bbbb_unitary)

assert  aaaa_sv.equiv(bbbb_sv)
```

**Comment by BankNatchapol** [comment]
Thank you
