### ISSUE TITLE
Transpiler performance improvement for current hardware

### ISSUE THREAD

**Issue by proeseler** [Qiskit/qiskit#12476]
### What should we add?

It could be that this is actually no problem and there is a more efficient way. I am currently building software for the QC Heron and try to minimize the depth. While plotting components of the circuit I recognized that consecutive Rz gates are not merged and I am wondering why? Here is an example code

```python
from qiskit import QuantumCircuit
from qiskit.transpiler.preset_passmanagers import generate_preset_pass_manager
from qiskit.circuit import ParameterVector
from qiskit.providers.fake_provider import GenericBackendV2

params = ParameterVector(f"θ", length=3)
qc = QuantumCircuit(1)
qc.rx(params[0], 0)
qc.u(params[0], params[1], params[2], 0)
backend = GenericBackendV2(num_qubits=2, basis_gates=["id", "rz", "sx", "x", "cz"])
pm = generate_preset_pass_manager(backend=backend, optimization_level=3)
isa_circuit = pm.run(qc)
print("Depth: ", isa_circuit.depth())
print(isa_circuit)
```

Here is the circuit output:
<img width="607" alt="image" src="https://github.com/Qiskit/qiskit/assets/148069723/5a0aa13f-0d07-45ba-bbe9-175cf0b68883">
Or using the crx gate:
<img width="749" alt="image" src="https://github.com/Qiskit/qiskit/assets/148069723/7f2daa01-aedb-45c1-aad5-7ed2e4c3eb16">

**Comment by mtreinish** [comment]
The underlying issue is that you're using unbound parameters in your circuit. All the peephole optimization passes in the preset pass managers work numerically (typically with a unitary matrix representation of the gate and synthesizing that). When you introduce an unbound parameters this precludes that approach, and in general symbolic manipulation and optimization isn't easy. There are definitely other open issues discussing this (although my searching ability is weak today and I can't find the links) but afaik there hasn't been any clear general solution. 

That being said in this case specifically you could do it fairly easily by summing the angles because it's just a run of rz gates, but if there was a mix of different 1q gates that approach wouldn't work. If you wanted to clean that up you could pretty easily add a custom pass to your pass manager to do that. Something like:

```py
from qiskit.transpiler.basepasses import TransformationPass
from qiskit.circuit.library import RZGate

class ContractRZGate(TransformationPass):
    def run(self, dag):
        rz_runs = dag.collect_runs(["rz"])
        for run in rz_runs:
            angle = 0
            for node in run:
                angle += node.op.params[0]
            new_op = RZGate(angle)
            dag.replace_block_with_op(run, new_op, {run[0].qargs[0]: 0}, False)
        return dag
```

Then just run:

```python
pm.optimization.append(ContractRZGate())
```
before calling run in your above example.

However, on the current IBM backends the RZ gates are done virtually so there is no error associated with them so having a few extra rz gates typically doesn't hurt anything. You can always confirm this by inspecting the backend's target and looking at the error rates and durations for the rz gates and if they're zero there is no overhead from them.

**Comment by proeseler** [comment]
Thank you very much! I know that symbolic optimisation in general is anything but trivial. I was just wondering because it looked so trivial.
