### ISSUE TITLE
Gate parameter validation in Rust

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit#12508]
### What should we add?

Gates with parameters (e.g. RZGate) are not singleton and instantiation of the class is non-negligible overhead. However, recently I noticed that the `Gate.params` setter shows significant walltime in profiling due to the validation function written in Python

https://github.com/Qiskit/qiskit/blob/797bb285632a4b58c35c9e4cf5be44502b5bd78a/qiskit/circuit/gate.py#L241-L255

Since Rz can be heavily used in the parameterized circuits like twirling, it's worth considering implementing this in Rust to reduce instantiation overhead (or maybe add option to bypass).

**Comment by nkanazawa1989** [comment]
In this circuit I have roughly ~10k Rz gates.
![image](https://github.com/Qiskit/qiskit/assets/39517270/6a2c56ee-0439-4ae4-b042-1d30d2fc10bf)

**Comment by mtreinish** [comment]
I'm not sure there is anything for rust to fix here. The `validate_params` method is purely a python space construct, it's basically protection against a user doing something like: `RZGate("I am a valid angle")` or any other random input type because python lets you put anything you want. Even when we move to standard gates being defined in rust with: https://github.com/Qiskit/qiskit/pull/12459 we still need to rely on `Gate.validate_parameter` when user input is being done in Python.

In rust this wouldn't even be a concern because the program wouldn't compile if you put an invalid type on the instruction. Although in the model from #12459 for backwards compatibility we have to allow any python object as a parameter type because a Python defined gate can contain any object as it's parameter (for example `UnitaryGate` can contain a numpy array).

In #12459 where I was able to skip validation was if the gate object is being created from rust, then we know it's already valid because it's been validated once before after being put on the circuit (although that validation was from `validate_params`). I think the only way you can avoid this overhead is after #12459 merges you can construct a `CircuitInstruction` manually with: `CircuitInstruction(qiskit._accelerate.circuit.StandardGate.RZGate, params=[3.14159], qubits=qargs)` and pass that directly to `QuantumCircuit._append` That would bypass all the validation, but then the burden is on you as the user to assert the parameters are valid because `CircuitInstruction` doesn't check anything.

**Comment by nkanazawa1989** [comment]
I wonder if we can do something like pydantic where type validation is written in Rust (or maybe internally using pydantic). It would be great if the Gate constructor has an option to bypass validation, or factory method for expert users who doesn't need automatic validation.

**Comment by jakelishman** [comment]
Naoki: for your immediate purposes, can you try moving the line `if isinstance(parameter, (int, float))` up to the top of the function, and changing it to `if isinstance(parameter, (float, int))`?  If that's enough for your immediate purposes (it'll save 2 `isinstance` checks per call for most cases), we can do that in the short term.

**Comment by jakelishman** [comment]
For fast-path constructors and whatnot, we'll likely grow a lot more of those a lot faster as we move more things to Rust - it's probably just going to get in the way trying to do it in Python space right now, since doing basically anything else with the circuit is likely to dominate the runtime over this.

**Comment by nkanazawa1989** [comment]
> Naoki: for your immediate purposes, can you try moving the line if isinstance(parameter, (int, float)) up to the top of the function, and changing it to if isinstance(parameter, (float, int))? If that's enough for your immediate purposes (it'll save 2 isinstance checks per call for most cases), we can do that in the short term.

That's neat! Since this is an extreme case of 10-100k gates with fixed parameters, the priority is not quite high. If you have fundamentally different solution with the Rust core that would be more appreciated.

**Comment by jakelishman** [comment]
The trick really is that just moving this function naively into Rust wouldn't help. The execution of the Python bytecode to implement the `isinstance` calls and the conditional branches will not be significantly slower than having the same code written in Rust.  If anything, it might be slightly slower, because we'd be calling the Python C API from an unfavoured position, rather than being baked into the full interpreter.

The only real way to speed this code up is to not do it at all.  The most reasonable path we have towards having an interface where that's a bit more possible (without introducing a lot of ways to shoot yourself in the foot) is to introduce alternative constructors or something for the standard gates, once we've got the Rust-space components in place.

**Comment by jakelishman** [comment]
For this setup:
```python
import itertools
from qiskit.circuit import RZGate

%timeit [RZGate(0.0) for _ in itertools.repeat(None, 1_000_000)]
```
I find reorganising `Gate.validate_parameter` to check the `float` first can get about an 8% speedup on this microbenchmark, but in absolute terms that's still 100ms over one million gates.  It's pretty entirely just not a bottleneck; the 100ms is nearly unobservable as soon as you start adding the gates to a circuit.  Changing `validate_parameter` to be simply `return parameter` is not dissimilar to putting the `float` check first in this case (you get maybe a 1-2% additional speedup).

I think your benchmarking here might be overstating the cost of `validate_parameter`; `cProfile` will fundamentally have an oversized impact on small Python functions and on access to `property` fields, and does not trigger at all when inside Rust code.  I think what you're really seeing is that _anything_ written in Python will appear to be much worse in `cProfile` than it is in practice, because you're mostly seeing the `cProfile` overhead.

**Comment by nkanazawa1989** [comment]
cProfile overhead makes a lot of sense. I wondered why this simple Python setter took such long time (I should have measured pure walltime with timeit as you did). 

> The only real way to speed this code up is to not do it at all.

Yes. I hope Qiskit will provide an option to bypass unnecessary validations. I'm not sure which is the best way though -- writing everything in Rust vs adding expert's method in Python with no type safety.

Anyways let me close this issue because likely I overestimated the impact of validation.
