### ISSUE TITLE
Classical function documentation needs a warning about Tweedledum support

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#12589]
### Environment

- **Qiskit version**: 1.1
- **Python version**: 3.12
- **Operating system**: 

### What is happening?

Trying to execute the code examples here: https://docs.quantum.ibm.com/api/qiskit/classicalfunction reveals that Tweedledum installation is broken:         

 validate(subset, filepath)
        File "/tmp/pip-build-env-dbmrjg5m/overlay/lib/python3.12/site-packages/setuptools/config/pyprojecttoml.py", line 57, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project`.
      configuration error: `project` must contain ['name'] properties

### How can we reproduce the issue?

Try to run the code on this page  https://docs.quantum.ibm.com/api/qiskit/classicalfunction

### What should happen?

It should work

### Any suggestions?

I guess the requirements.txt file says it only works for < Py311, but there in no mention of this in the docs, and Qiskit officially supports 3.11 and 3.12

**Comment by jakelishman** [comment]
Use of the underlying capability is a hard problem that we don't really have a solution to at the moment.  Tweedledum is de facto dead now, with no apparent possibility of resurrection.  It doesn't support Python 3.11 or newer at all (and I'm not sure if its wheels even work on macOS ARM - they certainly didn't for a long time).  Fwiw, we explicitly marked `tweedledum` in the package metadata as providing optional-only functionality several versions back (Terra 0.23 or something), because we had no way of supporting it in the core library - we didn't want to remove the wrapper code from Qiskit in case people were still using it, but we did move it into a lower support tier of "optional dependencies", which are dependent on a user being able to install the dependency on their system.

Fwiw, docstring testing here wouldn't change anything much: those examples _do_ work if you can get Tweedledum installed, which our docs-build configuration does.  The immediate problem is that _your_ Tweedledum installation is broken:

![Screenshot 2024-06-17 at 16 43 56](https://github.com/Qiskit/qiskit/assets/5968590/90bc4074-7f61-4272-8838-ee288228eeba)


---

What we can do immediately for the documentation here is to put a note at the top of the `qiskit.circuit.classical_function` module-level documentation that this uses optional functionality and requires `tweedledum`, which isn't available on all platforms.  Longer term, we need to transition to a world where we don't use `tweedledum` at all, and for that we need to work out what prioritisation and support we can commit to for `PhaseOracle`.

**Comment by 1ucian0** [comment]
I think the warning not on top makes sense model makes sense. The [`warning` sphinx directive](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-warning) can be used for that. Something like:
> This functionality requires `tweedledum` package, which isn't available on all platforms. See https://github.com/boschmitt/tweedledum/tree/master?tab=readme-ov-file#installation for more details.

Tagging this as `good first issue`

**Comment by arujjval** [comment]
Since this issue is regarding documentation, I think we should move it to `qiskit/documentation` repo.

**Comment by jakelishman** [comment]
The documentation in question is API documentation that's built from this repo.

**Comment by weechinghwa** [comment]
Hi hi, I am interested in working on this. Can I be assigned?
