### ISSUE TITLE
CircuitInstruction qarg type changed without communication

### ISSUE THREAD

**Issue by nkanazawa1989** [Qiskit/qiskit#12626]
### Environment

- **Qiskit version**: main
- **Python version**: 
- **Operating system**: 

### What is happening?

CircuitInstruction qarg type is suddenly changed.

![image](https://github.com/Qiskit/qiskit/assets/39517270/5ea1b532-d2b5-4215-abff-554b2e22643c)

![image](https://github.com/Qiskit/qiskit/assets/39517270/f59b2984-3a9f-4910-bd91-0f01eb86574c)

This can cause problem in unittest if one is testing instruction qubits without typecast.

### How can we reproduce the issue?

See above screenshot

### What should happen?

Data type must be preserved, or change must be mentioned in the release note

**Comment by jakelishman** [comment]
Can you test `data[0].qubits`? Hopefully the type of that is still `tuple`. Even so, we should fix this.

Fwiw, treated `CircuitInstruction` as a 3-tuple with list elements (rather than using the attribute accessors) is a legacy backwards-compatible behaviour that comes with a runtime penalty. It was added during the switch of the type of the circuit data 2 years ago. We probably should have deprecated and removed it for 1.0, but forgot.

Either way, the type shouldn't have changed while it is supported,band we can get that fixed.
