### ISSUE TITLE
AnalysisPass API run refers to DAG input

### ISSUE THREAD

**Issue by KelleClark** [Qiskit/qiskit#12793]
### Environment

- **Qiskit version**: 
- **Python version**: 
- **Operating system**: 

### What is happening?

API content for AnalysisPass refers to DAG instead of the QC that I believe is the intended parameter to run on.

### How can we reproduce the issue?

https://docs.quantum.ibm.com/api/qiskit/qiskit.transpiler.AnalysisPass

### What should happen?

I believe that the content should relect that a quantum circuit is sent in during these method calls for the pass to run against.

### Any suggestions?

I have never ever in my life made one of these issues on github, please give guidance if I have done this incorrectly!

**Comment by jakelishman** [comment]
Sorry for the delay in responding here.  `AnalysisPass` and `TransformationPass` both operate natively on `DAGCircuit`, which is Qiskit's compiler IR rather than the tree-like `QuantumCircuit`.  The compiler passes can all behave like regular Python callables that accept a `QuantumCircuit`, but natively all their methods are defined in terms of `DAGCircuit`.
