### ISSUE TITLE
several `SparsePauliOp` methods ignore `self.paulis.phase`

### ISSUE THREAD

**Issue by aeddins-ibm** [Qiskit/qiskit#12883]
### Environment

- **Qiskit version**: 1.1.1
- **Python version**: 3.11.6
- **Operating system**: macos

### What is happening?

If I understand it right, `SparsePauliOp.simplify()` does not correctly take into account the `phase` attribute of its underlying `PauliList`.

The same also seems true for several `SparsePauliOp` methods under the header "LinearOp Methods", like `conjugate`, and `adjoint`, which update `self.coeffs` but AFAIK do not look at `self.paulis.phase`.

(I haven't looked exhaustively for other methods that do not handle `paulis.phase`.)

### How can we reproduce the issue?

For example, define a `SparsePauliOp`, and then set its `paulis` attribute to a new value with nonzero `phase`:
```
spo = qi.SparsePauliOp(['X', 'X'])
spo.paulis = ['X','-X']
print(spo)
```
```
SparsePauliOp(['X', '-X'],
              coeffs=[1.+0.j, 1.+0.j])
```
So far so good. But now call simplify:
```
spo.simplify()
```
```
SparsePauliOp(['X'],
              coeffs=[2.+0.j])
```
AFAIK this is incorrect. 

### What should happen?

The example above should instead match this result where we construct the SPO differently:
```
spo_2 = qi.SparsePauliOp(['X','-X'])
spo_2.simplify()
```
```
SparsePauliOp(['I'],
              coeffs=[0.+0.j])
```

### Any suggestions?

Either we need to fix all the methods to consider `paulis.phase`, or (probably better) we need to more strictly require that the `paulis` attribute never has any phase, e.g. updating the `paulis()` setter to move the phase into the `coeffs` (don't know what else would need to change).

Another example:
```
spo_1 = qi.SparsePauliOp(['X'])
spo_1.paulis = qi.PauliList(['-1jX'])
spo_1
```
```
SparsePauliOp(['-iX'],
              coeffs=[1.+0.j])
```
Now try `conjugate()`:
```
spo_1.conjugate()
```
```
SparsePauliOp(['-iX'],
              coeffs=[1.-0.j])
```

**Comment by jakelishman** [comment]
I think your idea to ensure the `phase` stays zero is the right thing for `SparsePauliOp`.  It's not great that the implementation of the class uses a backing data structure (`PauliList`) that allows a phase in the operators, really, given that the SPO handling is obviously very different to that of "Pauli group but closed under matrix multiplication" that `PauliList` represents.

If/when we change up how `SparsePauliOp` is stored in memory, we definitely should be looking to remove the `phase` field entirely, since it's an unnecessary complication on top of the existing `coeffs`.

**Comment by aeddins-ibm** [comment]
Thanks Jake, I'm looking into updating the setter. Can I get your thoughts on another detail?

It would be nice to avoid copying the input `PauliList` in case it's very large. But we also don't want to immediately mutate the input by setting its phase to 0. One solution is to use `PauliList.from_symplectic` and pass the `z` and `x` parts of the input, but not the phase.

This seems a little weird, since the input `PauliList` will be modified by subsequent modifications of `self.paulis.x` (or `z`), but not by modifications of `self.paulis.phase`.

Does this approach sound OK? Or do you think it would it be better just to copy the input?

[Update: In the PR, I'm now taking the approach of modifying the input and raising a warning.]

**Comment by jakelishman** [comment]
Sorry, forgot to respond.

We have an `ignore_phase` argument to the `SparsePauliOp` constructor that can be used when the caller knows that the actual phase is 0.  If a user is using the `SparsePauliOp` setter, it's fine to mutate what they give us (as you did), because they're giving us ownership of it.  A user of `SparsePauliOp` shouldn't be mutating `self.paulis` themselves without maintaining the invariants of `SparsePauliOp` (e.g. that the phase remains zero). It's annoying that the current system makes that a bit harder / more expensive to do that, but I'd hope that it isn't a real bottleneck.  There's probably other stuff to do with `SparsePauliOp` that's _more_ of a bottleneck, at least.
