### ISSUE TITLE
Deprecate CU1Gate

### ISSUE THREAD

**Issue by kevinsung** [Qiskit/qiskit#12993]
U1Gate is deprecated, so it seems sensible that CU1Gate should also be deprecated. I'm looking at the docs, where U1Gate has a deprecation warning but CU1Gate does not:
- https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.U1Gate
- https://docs.quantum.ibm.com/api/qiskit/qiskit.circuit.library.CU1Gate

**Comment by jakelishman** [comment]
This seems sensible - `CPhaseGate` is a direct replacement.  Fwiw, we didn't deprecate `U1Gate` and friends formally in code, they're just deprecated by the documentation notice.  The reason is roughly that there's still a lot of extant circuits / OQ2 code / etc out there that uses them, and keeping the gate class around so they can still be represented doesn't really hurt us.

We did deprecate (and remove) the circuit methods `u1`, `u2` and `u3`, though, and I think deprecating and removing `QuantumCircuit.cu1` would be equally appropriate.

There is the awkward question about `CU3Gate`, though; we don't have a direct replacement for that (`CUGate` exists, but it's a lot more awkward to use because it breaks the typical controlled-gate flow by adding in a control-phase parameter).

**Comment by Cryoris** [comment]
> There is the awkward question about CU3Gate, though; we don't have a direct replacement for that (CUGate exists, but it's a lot more awkward to use because it breaks the typical controlled-gate flow by adding in a control-phase parameter).

True, though we're replacing calling `CU3Gate` directly, which could be (almost) directly replaced with `CUGate`, no?

**Comment by melechlapson** [comment]
Hi @kevinsung  @jakelishman I can work on this

**Comment by Cryoris** [comment]
Sounds good @melechlapson, let us know if you want to discuss something -- otherwise @jakelishman's comment above points out some places to start 🙂

**Comment by melechlapson** [comment]
@Cryoris Should I add a deprecation warning to `MCU1` as well?

**Comment by Cryoris** [comment]
Yes, as `MCPhaseGate` is a direct replacement we can also deprecate `MCU1Gate` 👍🏻

**Comment by melechlapson** [comment]
> We did deprecate (and remove) the circuit methods u1, u2 and u3, though, and I think deprecating and removing QuantumCircuit.cu1 would be equally appropriate.

@jakelishman  Isn't `QuantumCircuit.cu1`  already removed and deprecated? It's just the CU1Gate that remains

**Comment by melechlapson** [comment]
@Cryoris I opened https://github.com/Qiskit/qiskit/pull/13115 to address this. Could you review when you have time?

**Comment by cameron-d28** [comment]
make sure you link it to this pull request @melechlapson or else it likely can't be found.

**Comment by alphashiv27** [comment]
@Cryoris  [#13115 ](https://github.com/Qiskit/qiskit/pull/13115) was merged, however this issue is still open, is this issue yet to be resolved?

**Comment by Cryoris** [comment]
@alphashiv27 it seems we just forgot to link the PR to this issue -- thanks for the reminder!
