### ISSUE TITLE
Store a `Var(u32)` type for the `Wire::Var` variant in the rust DAGCircuit

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit#13027]
### What should we add?

Right now the DAGCircuit's edge weight type is the enum `Wire` which contains a u32 newtype index for qubits and clbits, as well as a `PyObject`  for `Var` edges in the DAG. However, the u32 newtype index `Qubit` and `Clbit` are just indices for `BitData` which is a mapping of integer indices to `PyObject`. In the case of `Qubit` and `Clbit` it's for the python space qubit and clbit classes. We should be leveraging the same infrastructure for `Var`s too as this would shrink our memory overhead for `DAGCircuit` pretty substantially as the  edge size would be 50% smaller (64bits per edge instead of 128bits as it is currently).

To do this we need to add a new index newtype `Var` to indicate a var instance in the circuit, and then add a new `BitData` field to the `DAGCircuit` struct where we track new vars as they're added to the circuit. Then update the `Wire` enum to store the `Var` type instead of a `PyObject`. This will require updating anything in `DAGCircuit` that is interacting with Var wires currently.

While the plan is to port the `Var` type to rust before too long, we can still leverage the `Var` newtype as an index for edge weights after that migration occurs. Instead of using a `BitData` for the mapping we can instead just using an `IndexMap` or a `HashMap`.

**Comment by jlapeyre** [comment]
I'm looking for any structural differences between `Var` and the `Qubit`/`Clbit` that might prevent using everywhere the same structures for tracking them. I don't find any yet, but may need to backtrack in #13048 if I run into such a difference.

Just for a sanity check I'll list some other structures that also must be changed to parallel the treatment of the bits.
* `VarIn` and `VarOut` in `pub enum NodeType {`
* Struct field `var_io_map: Vec<[NodeIndex; 2]>` rather than existing `var_input_map` and `var_output_map`. There is a comment noting that the latter two should be removed when `Var` is ported to rust. But here we are removing them sooner just to track Variables by indexing into  a container.

A couple of other issues
* We might get by with 16 bit indices for `Var`. But I guess that even if  we don't need 64KiB of `Var`s today, we will tomorrow.
* Still I see `32` hardcoded in many places even though we have `type BitType = u32`. For example, it seems better to write `Qubit(idx as BitType)` rather than `as u32`. Ideally, we could change the width in just one place if necessary.
* `BitType` (and related identifiers) are now misnomers. It's probably better to rename them rather than confuse future readers of the code.
