### ISSUE TITLE
Transpiler fails to simplify gates with parameters

### ISSUE THREAD

**Issue by natestemen** [Qiskit/qiskit#13442]
### Environment

- **Qiskit version**: 1.2.4
- **Python version**: 3.12.7
- **Operating system**: MacOS Sonoma 14.2.1

### What is happening?

The qiskit transpiler is failing to simplify/combine like gates where one of them is symbolic.

### How can we reproduce the issue?

```python
from qiskit import QuantumCircuit
from qiskit.circuit import Parameter
from qiskit.transpiler import PassManager
from qiskit.transpiler.passes Optimize1qGatesDecomposition

import numpy as np

x = Parameter("x")

test = QuantumCircuit(1)
test.rz(np.pi/2, 0)
test.rz(x, 0)
test.rz(np.pi/2, 0)

pm = PassManager(
    [
        Optimize1qGatesDecomposition(target=backend.target),
    ]
)

circuit = pm.run(test)

print(circuit)

#    ┌─────────┐┌───────┐┌─────────┐
# q: ┤ Rz(π/2) ├┤ Rz(x) ├┤ Rz(π/2) ├
#    └─────────┘└───────┘└─────────┘
```

### What should happen?

I expected the three gates to be combined into a single $R_z$ gate.

```python
print(circuit)

#    ┌───────────┐
# q: ┤ Rz(x + π) ├
#    └───────────┘
```

### Any suggestions?

cc @willzeng

**Comment by Cryoris** [comment]
We exclude parameterized gates from 1-qubit gate optimizations, since handling the symbolic expressions that could emerge can become a bottleneck. In your particular case the expression is simple, but that can change in larger circuits. Instead it would likely be faster to re-compile the circuit, once all values are fully assigned.

**Comment by natestemen** [comment]
Makes sense! I was just surprised because it doesn't allow for me to get accurate understanding of the depth of my circuit ahead of parameter binding.

**Comment by Cryoris** [comment]
Yes that's correct, though binding to dummy parameters should be fast if you're interested in the circuit properties before sending it off to the hardware.

As side note, if you run the full transpile function it should be able to merge the 2 non-parameterized RZ gates into one, since the commutation analysis knows how to handle parameterized gates.
