### ISSUE TITLE
Allow access to PyDiGraph indices in DAGCircuit

### ISSUE THREAD

**Issue by BarakKatzir** [Qiskit/qiskit#13456]
### What should we add?

I noticed that in `qiskit==v1.3.0rc1` the `DAGCircuit` class was oxidized which is great!
However, I previously used the underlying node indices of the `PyDiGraph` object via the private `_multi_graph` attribute, mainly for `__getitem__`.

I was wondering is it possible to re-expose the underlying `PyDiGraph` of a `DAGCircuit`, or perhaps just add a `__getitem__` / `get_by_node_id` method. 
P.S. I noticed that `_node_id` is still present on the DAGNode objects.

This will allow me to create a collection node indices instead of more hefty DAGNodes which will be copied in multiprocessing.

**Comment by mtreinish** [comment]
There is a method `DAGCircuit.node()` which takes a node id and returns the `DAGNode` object. I believe this is what you're looking for. 

Unfortunately there isn't a way to expose `._multi_graph` anymore because we're not using a python space rustworkx `PyDiGraph` graph object internally anymore so there isn't anything to expose there. That's why we deleted the private attribute because it's never used anymore.
