### ISSUE TITLE
Add Turkish Language

### ISSUE THREAD

**Issue by Ayshine** [Qiskit/qiskit#648]
I would like to contrıbute the translation project as Team Lead. 
Would it be possible to add the Turkish language?
https://crowdin.com/project/qiskit-docs

**Comment by SooluThomas** [comment]
Hi @Ayshine, Thank you for your interest in contributing to Qiskit Localization. Have you read the descriptions of the different roles in the [Blog Post](https://medium.com/qiskit/qiskit-in-my-language-is-qiskit-73d4626a99d3) (How to get involved section)

To get a language started, we need to have someone who will commit to being the translation lead, then there needs to be at least one proofreader to get a language started.
Which role are you interested in?

Also, if there are other volunteers to contribute to the same please use this issue to confirm their roles.

We really appreciate you volunteering to contribute. 😊

**Comment by mrek235** [comment]
Hello,

I would like to join the Turkish Localization Team as a translator.

**Comment by fsdundar** [comment]
I am Furkan Semih Dündar and have a PhD in physics. I am willing to contribute to Turkish localization/translation as a proof reader.

**Comment by Eymay** [comment]
I am Mehmet Eymen Ünay, I want to contribute Turkish translation as a translator

**Comment by RuneKingThor** [comment]
I am Berksu Ant Solmaz, I would like to contribute Turkish Translation as a Translator

**Comment by lzdanski** [comment]
Hi everyone, thank you so much for your enthusiasm! We're really excited to get this work moving along. Since we received a number of new language requests simultaneously, I'll be reaching out to the translation lead with some info, and then the Qiskit docs team will start the projects in CrowdIn. 

Be sure to check back on this issue for updates. When we open Turkish for translation, I will post a link here to the project and instructions for signing up/making a PR to the Contributor doc! Thank you for your patience as we get this started.

**Comment by elifsudegokay** [comment]
Hi,

I am Elif Sude Gökay I would like to join the Turkish Localization Team as a translator.

**Comment by emretaylanduman** [comment]
Hey everyone! Im Emre Phd student in Bioinformatics. I will be happy to contribute to localization team as translator or proofreader :grin:

**Comment by lzdanski** [comment]
@Ayshine, I sent you a quick message! 

I'm trying to get new language projects up this week :) Thank you again for your patience! We're really excited to work with you.

**Comment by nonhermitian** [comment]
Can you please move this issue here: https://github.com/Qiskit/qiskit-translations if needed
