### ISSUE TITLE
Using unroller translation method gives error on simple circuits

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#6668]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python

qc = QuantumCircuit(2)
qc.x(0)
qc.cz(0,1)
qc.delay(100, 0, 'us')
qc.measure_all()

trans_qc = transpile(qc, backend, translation_method='unroller')

```

gives

QiskitError: "Error decomposing node h: 'NoneType' object has no attribute 'global_phase'"

### Steps to reproduce the problem
Run above.  In this example it was targeting the IBM Athens system.

**Comment by ajavadia** [comment]
agree this is a bug. it is caused by unconditional access to `gate.definition.global_phase` and `gate.definition.data`, not taking into account that a definition may be None.

Looks like introduced here: https://github.com/Qiskit/qiskit-terra/pull/6155
@georgios-ts can you take a look?

**Comment by georgios-ts** [comment]
I don't think this is really a bug but rather a limitation of the `Unroller` . It is described here  https://github.com/Qiskit/qiskit-terra/issues/5840#issuecomment-778311046 and the error message has since then improved.

**Comment by nonhermitian** [comment]
This is confusing. H is one of the most commonly used gates out there and yet it is expected to fail. It is even more confusing because "unrolling" is what the change to basis gates was called in the past. What is the point of this option if it fails on something so trivial?

**Comment by ajavadia** [comment]
@georgios-ts Yes unroller is kind of pointless and should really be removed as a translation method (@kdk can we do this), but it did not raise this kind of error before the global phase additions. 

Why can't it be fixed by just simply making sure that you don't access the global_phase unconditionally [here](https://github.com/Qiskit/qiskit-terra/blob/cea50ed6f3bf6632a2f80c5e59756ebf5461df21/qiskit/transpiler/passes/basis/unroller.py#L73) (and a bunch of other places)?

If the unroller hits a node with a definition of None, then it should stop there. It is either in basis (which is good), or not (which should just say no unrolling possible).

**Comment by nonhermitian** [comment]
This can be closed
