### ISSUE TITLE
Transpiler removes resets at beginning of circuits unless level=0

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#6943]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?

```python

qc = QuantumCircuit(5, 4)
qc.reset(range(5))
qc.x(4)
qc.h(range(5))
qc.cx(range(4), 4)
qc.draw()
qc.h(range(4))
qc.barrier()
qc.measure(range(4), range(4))
qc.draw('mpl')
```

![image](https://user-images.githubusercontent.com/1249193/130808128-8157593b-ee6d-4397-95ab-9c0743c59ae0.png)

becomes:

```python

backend = FakeCasablanca()
trans_qc = transpile(qc, backend)
trans_qc.draw('mpl')
```

![image](https://user-images.githubusercontent.com/1249193/130808205-c6ae3f2f-58a0-4cf6-bebc-60af8478929b.png)

### Steps to reproduce the problem
Run above at optimization levels 1->3.

### What is the expected behavior?
If the user explicitly puts resets at the beginning of a circuit they should remain there.  This is important as the unconditional reset done by default on IBM Quantum systems is not perfect, leading to state prep errors.  Adding a reset at the beginning of a circuit greatly suppresses these errors and is needed to get high-fidelity results.

### Suggested solutions
Do not remove resets at the beginning of circuits. i.e. do not run this `RemoveResetInZeroState`

**Comment by TheGupta2012** [comment]
I would like to take a look at this issue @nonhermitian! May I have a go at it?

**Comment by nonhermitian** [comment]
Well I think it likely needs a discussion first as it was explicitly set this way 2 years ago by @ajavadia and @1ucian0.  It does cause a noticeable performance degradation to remove resets.   So if explicitly put there, I would think they should be kept so.

**Comment by TheGupta2012** [comment]
Okay looking forward to hearing from them!

**Comment by TheGupta2012** [comment]
@nonhermitian were any final solutions thought of, for this bug? If yes, I would be happy to implement them here!

**Comment by ajavadia** [comment]
> Does this issue overlap with #5127 or #5921?

yes i think it is related. 

I'm ok disabling the `RemoveResetInZeroState` pass from preset passmanagers. It doesn't do much in the way of circuit optimization anyway, and may be surprising to users. (But I do think it is a valid compiler thing to do, and barriers are the correct way for users to  prevent the compiler from doing that.)

Longer term I think the correct thing to do is to alter the assumption that circuits always start in state zero. We already started down this path by making the drawers not put `|0>` in the beginning of the circuit. But this assumption requires some user preparation, mainly because they have to always put `.reset()` at the beginning of their circuit (otherwise the qubit starts at some unknown state which could be anything). Some users may actually not want to reset qubits, e.g. in restless schemes (but the vast majority do).

**Comment by taalexander** [comment]
I can confirm that this is still an issue.

**Comment by ajavadia** [comment]
let's just remove the `RemoveResetInZeroState` pass. It's kind of pointless I think. I think what it's doing is valid but don't see much use for it.
