### ISSUE TITLE
Default optimization level does not perform self-inverse gate cancellations

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#7016]
### Information

- **Qiskit Terra version**: latest
- **Python version**:
- **Operating system**:

### What is the current behavior?
```python

qc= QuantumCircuit(2)
qc.h(range(2))
qc.cz(0,1)
qc.draw()
```

```
     ┌───┐   
q_0: ┤ H ├─■─
     ├───┤ │ 
q_1: ┤ H ├─■─
     └───┘   
```

```python

transpile(qc, basis_gates=['h', 'cx']).draw()

```

```
     ┌───┐               
q_0: ┤ H ├───────■───────
     ├───┤┌───┐┌─┴─┐┌───┐
q_1: ┤ H ├┤ H ├┤ X ├┤ H ├
     └───┘└───┘└───┘└───┘
```

### What is the expected behavior?
I would expect the default level of optimization to remove trivial things like repeated H gates.

**Comment by kdk** [comment]
Work was recently started in this direction by @vadebayo49 (see #6855 and #6576 ) but there is still some work to be done before this can be utilized by the default optimization levels, namely a way to identify (either through gate annotations or a library) which gates and gate pairs are inverse.

**Comment by mtreinish** [comment]
This is caused by the `OneQubitEulerDecomposer` not knowing how to simplify things in terms of h (you can see a list of the basis it can work in here: https://qiskit.org/documentation/stubs/qiskit.quantum_info.OneQubitEulerDecomposer.html#qiskit.quantum_info.OneQubitEulerDecomposer). The level 1 optimization level doesn't contain any passes that know how to cancel two consecutive h gates. I think higher optimizations definitely will though. I also think https://github.com/Qiskit/qiskit-terra/pull/6992 will do this too (not sure if it's being added to level 1 though).

I think we need to re-evaluate which passes we include in the different optimization levels because I think we can get away with more optimization in level 1 than we have right now.

**Comment by nonhermitian** [comment]
It does work at level 2 and higher.  However, given that the vast majority of users just do `execute` at the default level, perhaps level 1 should be beefed up some as you suggest.
