### ISSUE TITLE
assign_parameters and bind_parameters do almost the same thing. Can they be merged?

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#7057]
mostly the title, can `qiskit.circuit.quantumcircuit.QuantumCircuit.assign_parameters` and `qiskit.circuit.quantumcircuit.QuantumCircuit.bind_parameters` be merged? Their names do not highlight their differences.

**Comment by jakelishman** [comment]
Really they do _exactly_ the same thing, except `bind` raises TypeError if any of the given values aren't numeric.  `bind_parameters` definitely seems like it could be removed, as long as we make sure there's a reliable way to query if a circuit contains unbound parameters.

**Comment by TheGupta2012** [comment]
@1ucian0 can I correct this?

**Comment by 1ucian0** [comment]
Let's allow some time for discussion on the preferred direction first, if you don't mind.

**Comment by kdk** [comment]
Agree these two strongly overlap now. There was originally a justification in #4037 for leaving them separate, in that the behavior of `assign_` was planned to evolve to include cases where assigning parameters would not necessarily remove them from the circuit, but leave them in place so that once a circuit was evaluated under a given parameterization, they could be re-assigned without requiring the circuit to be copied. This still seems like a valid use case, given the heavy performance cost of copying circuits.

@Cryoris Any thoughts on whether or not this something that's needed, and if so, if `assign_parameters`  (or somewhere else) is the right place for it?

**Comment by Cryoris** [comment]
> [...] where assigning parameters would not necessarily remove them from the circuit, but leave them in place so that once a circuit was evaluated under a given parameterization, they could be re-assigned without requiring the circuit to be copied

I think that's still a valid use-case. To clarify, we would distinguish into the following:
* assign: keep the original parameter and the value it currently holds
    ```python
    assign: qc(theta) -> qc(theta: 1)  (theta is assigned the value 1)
    ```
    and `qc.parameters` still returns `{theta}`. I can also go ahead and change it to something else `qc(theta: 1) -> qc(theta: - 1)`
* bind: overwrite the parameter value
    ```python
    assign: qc(theta) -> qc(1)  
    ```
    and `qc.parameters` returns the empty set.

Since I think this assigning makes only sense for numeric values (I cannot assign `theta: theta2`) we could alternatively also always use `assign` and add some other methods to "collapse" the parameters with their values. Like
```python
assign: qc(theta) -> qc(theta: 1)
collapse: qc(theta: 1) -> qc(1)
```

**Comment by wyqian1027** [comment]
I would not want them to be merged. For example, suppose you have an ansatz that takes two Parameters. With assign_parameters, I can use assign to get a different quantum circuit each time without the need to rebuild the circuit. With bind_parameters, the circuit is now concrete, I could not reuse it to bind some other parameter. Then I will have to rebuild it from scratch. I think these two methods are different and both useful.
