### ISSUE TITLE
Some internal polishing is needed in the QASM3 exporter

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit#7136]
This is a https://github.com/Qiskit/qiskit-terra/pull/6565 follow up

This particular issue tracks:
- [ ] The `GlobalNamespace._data` is horrendous and needs to be split. More [here](https://github.com/Qiskit/qiskit-terra/pull/6565#discussion_r669145097).  
- [ ] Merge `GlobalNamespace` and `Exporter`.
- [ ] Better Namespace validation and renaming, see [here](https://github.com/Qiskit/qiskit-terra/pull/6565#discussion_r714732791) and [here](https://github.com/Qiskit/qiskit-terra/pull/6565#discussion_r714733921).

**Comment by Ryand1234** [comment]
Hi @1ucian0, Can I work on this?

**Comment by jakelishman** [comment]
Hi @Ryand1234! This might not be the best choice for an external contributor, sorry - this issue is mostly a tracker for the core team, because we'll be making fairly heavy changes to the QASM 3 processing in Terra over the next few release cycles, and these changes will be part of it.  The changes needed for this issue are very major to a core deliverable in Terra 0.20 which will have quite a lot of activity, so it'll be a bit easier for us to manage if we keep this internal.

If you're looking for good issues, we have the ["good first issue" label](https://github.com/Qiskit/qiskit-terra/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) for issues that are good for first-time contributors, and the ["help wanted" label](https://github.com/Qiskit/qiskit-terra/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) for those with a bit more experience.  There's also ["short project"](https://github.com/Qiskit/qiskit-terra/issues?q=is%3Aissue+is%3Aopen+label%3A%22short+project%22), and these may require a fair amount of physics knowledge to handle.

**Comment by jakelishman** [comment]
#12776 addresses all the problems tracked by this issue.  There's still obviously polishing that could be done, but I've marked this issue as closed by #12776.
