### ISSUE TITLE
Subclasses of TwoQubitWeylDecomposition are not dill-serialisable

### ISSUE THREAD

**Issue by andrenmelo** [Qiskit/qiskit#7312]
### Environment

- **Qiskit Terra version**: e42e90bbe13c1fe0673d63654fe0682f31ff8acf
- **Python version**: 3.9.1
- **Operating system**: Mac OS Big Sur 11.3.1

### What is happening?

Any subclasses of `TwoQubitWeylDecomposition` are not serialisable.

### How can we reproduce the issue?

```python
import dill
import numpy as np
from qiskit.quantum_info.synthesis.two_qubit_decompose import TwoQubitWeylDecomposition

unitary = np.array([[0.70710678, 0, 0, -0.70710678j],
                    [0, 0.70710678, -0.70710678j, 0],
                    [0, -0.70710678j, 0.70710678, 0],
                    [-0.70710678j, 0, 0,  0.70710678]])
weyl = TwoQubitWeylDecomposition(unitary) # instantiates TwoQubitWeylControlledEquiv
dill.loads(dill.dumps(weyl))
```

will result in 

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-b24fd30371a4> in <module>
      8                     [-0.70710678j, 0, 0,  0.70710678]])
      9 weyl = TwoQubitWeylDecomposition(unitary) # instantiates TwoQubitWeylControlledEquiv
---> 10 dill.loads(dill.dumps(weyl))

~/miniconda3/envs/pulse/lib/python3.9/site-packages/dill/_dill.py in loads(str, ignore, **kwds)
    325     """
    326     file = StringIO(str)
--> 327     return load(file, ignore, **kwds)
    328 
    329 # def dumpzs(obj, protocol=None):

~/miniconda3/envs/pulse/lib/python3.9/site-packages/dill/_dill.py in load(file, ignore, **kwds)
    311     See :func:`loads` for keyword arguments.
    312     """
--> 313     return Unpickler(file, ignore=ignore, **kwds).load()
    314 
    315 def loads(str, ignore=None, **kwds):

~/miniconda3/envs/pulse/lib/python3.9/site-packages/dill/_dill.py in load(self)
    523 
    524     def load(self): #NOTE: if settings change, need to update attributes
--> 525         obj = StockUnpickler.load(self)
    526         if type(obj).__module__ == getattr(_main_module, '__name__', '__main__'):
    527             if not self._ignore:

~/miniconda3/envs/pulse/lib/python3.9/site-packages/qiskit/quantum_info/synthesis/two_qubit_decompose.py in <lambda>(cls, fidelity, *a, **k)
    129         Make explicitly-instantiated subclass __new__  call base __new__ with fidelity=None"""
    130         super().__init_subclass__(**kwargs)
--> 131         cls.__new__ = lambda cls, *a, fidelity=None, **k: TwoQubitWeylDecomposition.__new__(
    132             cls, *a, fidelity=None, **k
    133         )

TypeError: __new__() missing 1 required positional argument: 'unitary_matrix'
```

This becomes an issue when defining custom pass managers, e.g.

```python
from qiskit import QuantumCircuit
from qiskit.transpiler import PassManager
from qiskit.compiler.transpiler import _parse_transpile_args, level_3_pass_manager
from qiskit import Aer

qc = QuantumCircuit(1)
qc.x(0)

transpile_args = _parse_transpile_args([qc],
                                       Aer.get_backend('statevector_simulator'),
                                       None, None, None, None, None, None, None,
                                       None, None, None, None, None, None, None,
                                       None, None, None, "default", None)

pass_manager_config = transpile_args[0]['pass_manager_config']
pm = level_3_pass_manager(pass_manager_config)
pm.run([qc]*10)
```

This throws the same exception as above, because running several passes[ is done in parallel](https://github.com/Qiskit/qiskit-terra/blob/2eee56616d50a9e26756f855ef4aa0135920ad78/qiskit/transpiler/passmanager.py#L229-L255) and requires serialising the `PassManager`.

### What should happen?

Examples above should not fail.

**Comment by mtreinish** [comment]
Yeah, looking at the code the way the `PassManager` class is doing the parallel dispatch it's incorrect and could never work unless we were guaranteeing all Passes are pickleable which we traditionally haven't enforced. This was never caught because the `transpile()` path does it's own parallelism: https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/compiler/transpiler.py#L321-L322 where it integrates the pass manager construction into the child process.

For this specific issue the quick fix is to add either a `__getstate__`/`__setstate__` or `__reduce__` method to `TwoQubitWeylDecomposition` so that pickle is able to deal with the custom `__new__` and subclassing logic that the class implements. This is simple and should fix this specific issue.

But this raises a larger issue around how we do parallel dispatch in the transpiler. If we just want to do it at the `transpile()` function level then we should remove the support for parallel dispatch from the `passmanager.run()` method so that individual passmanager instances only run serially and we rely on an outer function to do parallel dispatch. Or if we want to enable standalone passmanagers to run in parallel we should change `transpile()` to leverage the same parallelism path and let the `passmanager.run()` instance control it's own dispatch. Right now having two different paths lets bugs like this slip through.

**Comment by levbishop** [comment]
I'll fix the `TwoQubitWeylDecomposition` pickle piece since its easy. Agree that there is a larger issue to discuss around parallelism

**Comment by mtreinish** [comment]
I'm going to close this issue. The decomposer is definitely pickleable now (and also now lives primarily in Rust) and for the larger parallelism questions we've basically more or less settled on the pattern I was describing 3 years ago. We've unified the parallel dispatch and only do it via `PassManager.run()` (which `transpile()` calls.
