### ISSUE TITLE
Add Korean Language to Localization

### ISSUE THREAD

**Issue by jinho10** [Qiskit/qiskit#732]
I am a qiskit advocate and would like to start contributing from the documentation. I would like to be a translation lead for my main role (translation experience), but at the same time I also want to perform as Translators and Proofreaders.

I already pull requested to add myself to the LOCALIZATION_CONTRIBUTOR

https://github.com/Qiskit/qiskit/pull/731

I am asking around my Korean community to join as well.

**Comment by sungcheolkim78** [comment]
I want to join as a translator and proofreader for the Korean language. 
I also requested to add myself to the LOCALIZATION_CONTRIBUTOR.

**Comment by lzdanski** [comment]
Hi, thank you so much for volunteering to work on translation! We're really excited to get this work moving along. Since we received a number of new language requests simultaneously, I'll be reaching out to the translation lead with some info, and then the Qiskit docs team will start the projects in CrowdIn. 

Be sure to check back on this issue for updates. When we open Korean for translation, I will post a link here to the project and instructions for signing up/making a PR to the Contributor doc! Thank you for your patience as we get this started.

**Comment by ssinji** [comment]
@lzdanski I'm also interested in volunteering this work and already submitted a PR (#740) Please keep me posted.

**Comment by jinho10** [comment]
@lzdanski do we have any update on this? can you share the ballpark timeline to get us started? no pressure.

**Comment by lzdanski** [comment]
Hi @jinho10 , @ssinji , @sungcheolkim78  the Qiskit Translation project for [Korean](https://crowdin.com/project/qiskit-docs/ko#) is now open on Crowdin! 

To join the project, follow [steps 4 and 5](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation) of the contributor guide. 

*Please be sure to include the [PR you made](https://github.com/Qiskit/qiskit/pulls) adding your name to the Localization Contributors file in the message body when you request to join*

**Comment by jinho10** [comment]
@lzdanski thanks for follow-up. I requested join. My username is `goodkorean`.

**Comment by nonhermitian** [comment]
Can you please move this issue here: https://github.com/Qiskit/qiskit-translations if needed
