### ISSUE TITLE
CUGate's params getter does not comply with circuit's assign_parameters

### ISSUE THREAD

**Issue by yjt98765** [Qiskit/qiskit#7326]
### Environment

- **Qiskit Terra version**: 0a10008
- **Python version**: 3.8.10 64-bit
- **Operating system**: windows 10 64-bit

### What is happening?

This issue is proposed based on the discussion under #7283, especially the [insight](https://github.com/Qiskit/qiskit-terra/issues/7283#issuecomment-981504394) of @jakelishman.

`CUGate` is the controlled version of `UGate`, a generic single-qubit rotation gate with 3 Euler angles. Most controlled gates have the same parameters as the base gate, but `CUGate` has an extra one: the global phase `γ`. To cope with this, `CUGate` uses a `@property` decorator to define a getter for the property `params`. This getter function creates a new array and returns it. It leads to problems that following operations may be applied to this newly created array instead of the real parameters of the `CUGate` object. For example, that happens in the function `QuantumCircuit.assign_parameters`, which is demonstrated in the following section.

The failure of `assign_parameters` on `CUGate` leads to another problem. Currently, a line is missing below [line 652](https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/circuit/library/standard_gates/equivalence_library.py#L652) in qiskit/circuit/library/standard_gates/equivalence_library.py.
```python
q = QuantumRegister(2, "q")
theta = Parameter("theta")
phi = Parameter("phi")
lam = Parameter("lam")
cu3_to_cu = QuantumCircuit(q)
cu3_to_cu.cu(theta, phi, lam, 0, 0, 1)
# should have another line:
# _sel.add_equivalence(CU3Gate(theta, phi, lam), cu3_to_cu)
```
If the `add_equivalence` function is added, the test [test_equivalence_phase](https://github.com/Qiskit/qiskit-terra/blob/main/test/python/circuit/test_gate_definitions.py#L301) would report a `TypeError` exception. `QuantumCircuit.assign_parameters` is called during the test, 

### How can we reproduce the issue?

```python
from qiskit.circuit import QuantumCircuit, Parameter
ps = [Parameter("t"), Parameter("p"), Parameter("l"), Parameter("g")]
qc = QuantumCircuit(2)
qc.cu(*ps, 0, 1)
qc.cu3(*ps[:3], 0, 1)
print(qc)
print(qc.assign_parameters(dict(zip(ps, [0.1, 0.2, 0.3, 0.4])), inplace=False))
```
The output is
```
q_0: ──────■─────────────■──────
     ┌─────┴──────┐┌─────┴─────┐
q_1: ┤ U(t,p,l,g) ├┤ U3(t,p,l) ├
     └────────────┘└───────────┘

q_0: ──────■────────────────■─────────
     ┌─────┴──────┐┌────────┴────────┐
q_1: ┤ U(t,p,l,g) ├┤ U3(0.1,0.2,0.3) ├
     └────────────┘└─────────────────┘
```
suggesting the assignment of CUGate is failed. Note that the parameters of the `U3Gate` have been assigned.

### What should happen?

The second circuit should be
```
q_0: ──────────■────────────────────■─────────
     ┌─────────┴──────────┐┌────────┴────────┐
q_1: ┤ U(0.1,0.2,0.3,0.4) ├┤ U3(0.1,0.2,0.3) ├
     └────────────────────┘└─────────────────┘
```

### Any suggestions?

Maybe remove the `γ` parameter from CUGate. The global phase is a property of quantum circuits. It is not a property of other gates. Adding this parameter to CUGate makes it different from the general cases and requires special processing, e.g., [here](https://github.com/Qiskit/qiskit-terra/blob/main/test/python/circuit/test_controlled_gate.py#L978) and [here](https://github.com/Qiskit/qiskit-terra/blob/main/test/python/circuit/test_controlled_gate.py#L1235).

**Comment by Cryoris** [comment]
We added the `gamma` parameter to the `CUGate` so that it represents a general 2 qubit gate, as discussed in https://github.com/Qiskit/qiskit-terra/issues/4106 🙂 Maybe another solution would be to just return the `params` stored in `CUGate` insted of going via the base gate which doesn't have the `gamma` parameter.

**Comment by jakelishman** [comment]
Perhaps calling it "global" phase is a bit misleading here (it's the phase of the controlled gate), but yeah, the gamma parameter needs to stay for now.  The main issue is [again :(] that we don't have a contract for what `Instruction.params` should contain, and how it should behave with respect to mutability.  `QuantumCircuit` assumes that it's a "true" attribute, and tries to write to it as if it is guaranteed to be a list, but that's probably not something it can assume.

The "bug" could either be that `CUGate` _most_ return a list-like object that backs _all_ its parameters (in which case we need to do what Julien said), or other places in Terra need to stop assuming that they can mutate the object.  They can write wholesale, perhaps (so they'll trigger the setter method), but they can't mutate.  This second form is more safe, but it likely has some performance implications, because we'd need to be reconstructing several lists/tuples each time.

**Comment by Cryoris** [comment]
Yep agreed, after #7087 we can hopefully start introducing more structure and determine which gates share which properties (-> e.g. standard gates that have free parameters).

**Comment by t-imamichi** [comment]
@jakelishman Parameter binding to cu does not look working. Is it related to this issue?

```python
from qiskit import QuantumCircuit
from qiskit.circuit import ParameterVector

qc = QuantumCircuit(2)
param = ParameterVector('t', 4)
qc.cu(param[0], param[1], param[2], param[3], 0, 1)

print('before')
print(qc)
print()

qc2 = qc.bind_parameters([1, 2, 3, 4])
print('after')
print(qc2)
```

output
```
before

q_0: ────────────■─────────────
     ┌───────────┴────────────┐
q_1: ┤ U(t[0],t[1],t[2],t[3]) ├
     └────────────────────────┘

after

q_0: ────────────■─────────────
     ┌───────────┴────────────┐
q_1: ┤ U(t[0],t[1],t[2],t[3]) ├
     └────────────────────────┘
```

**Comment by jakelishman** [comment]
Yeah, it's the same issue - `assign_parameters` / `bind_parameter` tries to mutate indices in the `CUGate.params` field, but the gate has a getter that produces a new list, not the actual array.  Julien at one point had a PR that added `assign_parameter` to `Instruction` instances so it could be overridden, but I don't know what happened to that.

**Comment by Cryoris** [comment]
It stalled since it introduce a small performance hit 😅 --> #7487

**Comment by t-imamichi** [comment]
Thank you for the information!
