### ISSUE TITLE
Implement `SparsePauliOp.assign_parameters`

### ISSUE THREAD

**Issue by mrossinek** [Qiskit/qiskit#8966]
### What should we add?

#8620 added support for `Parameter` objects to be used inside of `SparsePauliOp`s, porting this functionality from `opflow` to `quantum_info` and paving the way for a switch of the algorithms and application modules to be using purely `quantum_info` in the future.

However, once key functionality for this to be useful is still missing; and that is the implementation of `SparsePauliOp.assign_parameters`. Without it, there is no convenient way of actually using a parameterized `SparsePauliOp` instance.

**Comment by mrossinek** [comment]
Alright, thank you! :+1: 

Feel free to close this issue if you feel like this resolves it. I am open to whether or not this functionality should be added.

**Comment by woodsp-ibm** [comment]
When opflow was done with Parameter support we had consistency in the way the object supported Parameters with the same the methods as a parameterized circuit for the parameterized operator. My take is that it would nice to have the same support here with the Parameter support/objects Terra has. If you are allowing other types as coeffs then I agree the onus is on an end user. But for Parameter support my take would be to have the SparsePauliOp support it for consistency and ease of end user use.

**Comment by Cryoris** [comment]
I also think it would be good to have proper support of Qiskit's `Parameter` objects in the `SparsePauliOp`, as it is replacing how we used parameterized operators in Opflow. In several algorithms (e.g. QBMs in ML or time-evolution with time dependent Hamiltonians) we would need to assign parameters to the operators.

As Steve said already, we of course don't support binding any variable type but since the `Parameter` is Qiskit native I would expect support for that 😄 Also, the parameters should be bound in the same order as in the circuit 🙂

**Comment by ElePT** [comment]
Issue resolved by #9796.
