### ISSUE TITLE
QASM 3 exporter makes multiple definitions for same gate

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit#9428]
### Environment

- **Qiskit Terra version**: lastest
- **Python version**: 
- **Operating system**: 

### What is happening?

```python

qc = QuantumCircuit(2)
qc.rzz(1,0,1)
qc.rzz(1,0,1)
qc.rzz(1,0,1)
```
gives a unique QASM3 gate definition for each gate above even though they are identical.

```text
OPENQASM 3;
include "stdgates.inc";
gate rzz_4592196368(_gate_p_0) _gate_q_0, _gate_q_1 {
  cx _gate_q_0, _gate_q_1;
  rz(1) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
}
gate rzz_4592194880(_gate_p_0) _gate_q_0, _gate_q_1 {
  cx _gate_q_0, _gate_q_1;
  rz(1) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
}
gate rzz_4592190992(_gate_p_0) _gate_q_0, _gate_q_1 {
  cx _gate_q_0, _gate_q_1;
  rz(1) _gate_q_1;
  cx _gate_q_0, _gate_q_1;
}
qubit[2] _all_qubits;
let q = _all_qubits[0:1];
rzz_4592196368(1) q[0], q[1];
rzz_4592194880(1) q[0], q[1];
rzz_4592190992(1) q[0], q[1];
```

### How can we reproduce the issue?

Run above

### What should happen?

Ideally, every unique gate would have a single definition.

**Comment by jakelishman** [comment]
This behaviour is 100% non-ideal, but it's not strictly a _bug_ so much as a deliberate work-around for problems in the Qiskit data model right now.

The issue is that when the exporter encounters a gate with its parameters bound to real numeric values, there’s no proper way for it to retrieve a definition of the circuit that would apply to arbitrary (symbolic) parameters.  Since we can’t do that (and gates are even free to override their definitions, which we also wouldn’t be able to detect currently).  We can only get a version with the bound parameters right now, so to be safe, the exporter puts out a separate definition for each gate, if that gate isn’t in `stdgates.inc`.

I get that in this example, they’re all the same parameter so it’d be better if we recognised that, but unless there’s a serious need to fix that particular use-case right now, I wouldn’t have thought that that was super common.  Fixing it without fixing the general case would involve carrying around an extra nested dictionary, which isn’t very difficult, if getting “same gate, same parameters” unified immediately would be a big help.

(copied from slack discussions)

**Comment by jakelishman** [comment]
From offline discussions: I'll add some special cases to the OQ2 and OQ3 exporter paths to treat Qiskit standard-library gates specially with regard to parametrisation.  It's not perfect, but the general solution requires something like #7624.  That's a priority for Terra 0.24, but it's been pushed from several Terra releases now, and this should be a hopefully easy work-around that eases a lot of short-term pain.

**Comment by jakelishman** [comment]
This will be fixed for Qiskit standard-library gates, including the `rzz` mentioned in the top issue by #12776.  User-defined parametric gates will still not as well as we might like, but that's related to the problem in the data model alluded to above.
