### ISSUE TITLE
Sampler primitive in Terra does not support mid-circuit measurements

### ISSUE THREAD

**Issue by garrison** [Qiskit/qiskit#9657]
### What should we add?

The reference `Sampler` (in `qiskit.primitives`) does not support mid-circuit measurements.  However, other Samplers, including those provided by qiskit-aer and qiskit-ibm-runtime, do support mid-circuit measurements.

I understand the desire to keep the reference implementation simple, but it is hardly a _reference_ implementation if it only implements the Sampler for a subset of possible inputs.

This was previously discussed at https://github.com/Qiskit/qiskit-terra/pull/8708.  My goal here is to open a centralized place for discussion going forward

**Comment by garrison** [comment]
As for the question of "why don't you just use the Aer sampler instead?" ...

I'd like to calculate the exact probability of each outcome in a circuit with mid-circuit measurements.  ~~Aer cannot calculate exact probabilities of each classical register outcome, but the reference Sampler has this ability (set `shots=None`).~~  EDIT: Aer has the same problem as this package when `shots=None`: https://github.com/Qiskit/qiskit-aer/issues/1810.

**Comment by garrison** [comment]
I figured out and implemented a way to meet my current need by evolving the `Statevector` according to each instruction, and considering both outcomes each time there is a measurement in the circuit.  If desired, I could attempt to contribute this upstream to Qiskit Terra, so that we could close this issue.  This would also have the side effect of allowing unused bits in the classical registers, which is currently not supported:

https://github.com/Qiskit/qiskit-terra/blob/94e9480ddb5d1304a45ad8b463668ebe144a43d2/qiskit/primitives/sampler.py#L168-L173

**Comment by mtreinish** [comment]
I think this is reasonable to add to the `Sampler` class. That current restriction looks like it's only in place because of how the sampler goes from the probabilities to the expect bitstring and isn't really inherent to sampling. So if we can remove that and support midcircuit measurement that seems reasonable to me. @t-imamichi @ikkoham what do you think?

**Comment by t-imamichi** [comment]
Because the reference implementation `Sampler` and `Estimator` were developed before mid-circuit measurements were released. the reference `Sampler` and `Estimator` cannot handle mid-circuit measurements.
I recently opened #9692 to raise an error for `Estimator`.

Now that we have `BackendEstimator` and `BackendSampler`, it is an option to extend them to handle mid-circuit measurements and deprecate the current reference impl `Sampler` and `Estimator`. @ikkoham opened #9700 for the discussion.

**Comment by jacobwatkins1** [comment]
Hello, is there any update on this? I would like to use Sampler for an iterative phase estimation algorithm, which necessarily requires mid circuit measurements.

**Comment by garrison** [comment]
> I would like to use Sampler for an iterative phase estimation algorithm, which necessarily requires mid circuit measurements.

You could use Aer's sampler with `shots != None`.

**Comment by jacobwatkins1** [comment]
**Edit:** @garrison already noticed this prior to the comment below.

I am actually running into the same issue with the `qiskit_aer.primitives` `Sampler`. 

`QiskitError: 'Some classical bits are not used for measurements. The number of classical bits 4, the used classical bits set().'`

Here is the code generating the problem. It is pretty minimal. Using version >= 12 for `qiskit_aer` and 0.44.0 for `qiskit`:

![image](https://github.com/Qiskit/qiskit/assets/29473076/8cbc4678-ff80-4af0-bba7-d535fd55d70a)

**Comment by garrison** [comment]
> I am actually running into the same issue with the `qiskit_aer.primitives` `Sampler`.

The corresponding issue for `qiskit-aer` (which is triggered only when `shots=None`) is https://github.com/Qiskit/qiskit-aer/issues/1810.

**Comment by t-imamichi** [comment]
I close this because the Primitives V1 is deprecated #12575
